local L = AceLibrary("AceLocale-2.2"):new("QuestsFu_Comments")
L:RegisterTranslations("zhTW", function() return {
	["Comments"] = "備註",
	["Display quest comments"] = "顯示任務備註",
	["LightHeaded"] = "LightHeaded 資料庫",
	["Location unknown"] = "未知地區",
	["LightHeaded Info"] = "LightHeaded 資訊",
	["Quest ID: "] = "任務編號: ",
	["Shareable: "] = "可分享: ",
	["Level: "] = "等級: ",
	["Required Level: "] = "需要等級: ",
	["Starts: "] = "開始: ",
	["Ends: "] = "結束: ",
	["Experience: "] = "經驗值: ",
	["Reputation:"] = "聲望: ",
	["Quest Series:"] = "任務系列: ",
	["Quest "] = "任務 ",
	["LightHeaded Comments"] = "LightHeaded 備註",
	["No comments found..."] = "沒有備註...",
	["Comments are all from WowHead"] = "備註來源為 WowHead",
	["Yes"] = "是",
	["No"] = "否",
} end)
