--[[
****************************************************************************************

ARLLocals-deDE.lua

deDE localization strings for Ackis Recipe List

$Date: 2008-07-03 14:37:48 -0400 (Thu, 03 Jul 2008) $
$Rev: 77747 $

Original translated by: 
Currently maintaince by: 

Thank you all translators! (From Ackis)

****************************************************************************************
]]--
local L = LibStub("AceLocale-3.0"):NewLocale("Ackis Recipe List", "deDE", false);
if not L then return end

-- Options Categories
L["DISPLAY_OPTIONS"] = "Rezepte Scan Anzeige Optionen"
L["FILTER_OPTIONS"] = "Filteroptionen"
L["REP_OPTIONS"] = "Fraktionsoptionen"
L["Reputation"] = true
L["SORT_OPTIONS"] = "Sortierung der Rezeptliste"

-- Display Options
L["GUI_TOGGLE"] = "Schalte die Nutzung des GUIs an oder aus."
L["FILTERCOUNT_TOGGLE"] = "Gefilterte Rezepte zu den Gesamtrezepten zählen."
L["CLOSEGUI_TOGGLE"] = "Schließt das ARL Fenster, wenn das Handwerksfenster geschlossen wird."

-- Filtering Options
L["FACTION_TOGGLE"] = "Alle Fraktionen in den Scan einbeziehen."
L["PVP_TOGGLE"] = "Bezieht die PVP-Rezepte in den Scan ein."
L["CLASS_TOGGLE"] = "Alle Klassen in den Scan einbeziehen."
L["SPECIALITY_TOGGLE"] = "Alle Spezialisierungen in den Scan einbeziehen."
L["RAID_TOGGLE"] = "Schwer zu bekommende Rezepte aus Schlachtzügen in den Scan einbeziehen."
L["SKILL_TOGGLE"] = "Alle Skill Level in den Scan einbeziehen."

-- Sorting options
L["Name"] = "Name" 
L["Skill"] = "Skill"

-- Reputation Toggles
L["SPECIFIC_REP_TOGGLE"] = "inkl. %s."

-- Non-gui text
L["MissingFromDB"] = ": fehlt in der Datenbank. \nBitte informiere den Autor dieses Addons über das Rezept."
L["MissingRecipePrefix"] = "Fehlendes Rezept: "
L["InitiateScan"] = "Scanne %s auf fehlende Rezepte mit Skill Level %s.\n"
L["InitiateScanSpecial"] = "Scanne %s - %s auf fehlende Rezepte mit Skill Level level %s.\n"
L["RecipeListSummary"] = "\nDu kennst %s von %s Rezepten (%s%%).\nDir fehlen %s Rezepte."
L["UnknownTradeSkill"] = "Du hast ein Handwerksfenster geöffnet das nicht von diesem Addon unterstützt wird.  Die Handwerksfähigkeit ist %s.  Bitte kontaktiere den Autor dieses Addons mit dieser Information."
L["OpenTradeSkillWindow"] = "Bitte öffne ein Handwerksfenster zum Scannen."

-- GUI Text
L["Close"] = "Schließen"
L["NoObtain"] = "Keine Information verfügbar."
L["ScanButton"] = "Scan"
L["Scan Skills"] = "Rezeptscan"
L["Scan Skills Long"] = "Nach fehlenden Rezepten scannen."

-- Recipe Database
L["Trainer"] = "Lehrer"
L["LimitedSupply"] = "Eingeschränkter Händlerverkauf"
L["Vendor"] = "Händler"
L["Discovery"] = "Geistesblitz"
L["PVP"] = "PVP"
L["Raid"] = "Schlachtzug"

--Skillup Levels
L["Journeyman"] = "Geselle"
L["Expert"] = "Experte"
L["Artisan"] = "Fachmann"
L["Master"] = "Meister"

-- Common ways to obtain recipes
L["CWD"] = "Gewöhnlicher World Drop"
L["UWD"] = "Seltener World Drop"
L["RWD"] = "Rarer World Drop"
L["EWD"] = "Epischer World Drop"
L["BoE"] = "Gebunden beim Anlegen (BoE) Drop: "
L["BoP"] = "Gebunden beim Aufnehmen (BoP) Drop: "
L["DMCACHE"] = "Knot Zwingschraubs Behälter, Düsterbruch (Nord)"
L["Gordok Ogre Suit"] = "Ogeranzug der Gordok"
L["Gordok Ogre Suit Obt"] = "Questbelohnung: Der Ogeranzug der Gordok"
L["Spectral Essence Obt"] = "Questbelohnung: Kirtonos der Herold (erlaubt dir den Händler Magnus Frostrufer in der Nähe von Scholomance zu sehen)"
L["TrueBelieverQuest"] = "Questbelohnung: Wahrer Glauben - Seltener Drop von Entschlüsselte Ausschnitte des Wahren Glaubens"
L["QuestReward"] = "Questbelohnung: "

-- Raid Drop Obtain Info
L["MOLTENCORE"] = "BoP Mob Drop: Zufällige Bosse in MC."
L["AQ20/AQ40"] = "BoP Mob Drop: Zufällige Bosse in AQ20/AQ40."
L["ADNaxx"] = "Erlernbar von Meisterhandwerker Omarion im Todesritter Flügel von Naxxramas."
L["SSC/TKBoP"] = "BoP Mob Drop: Zufällige Bosse und Mobs in SSC/TK."
L["SSC/TKBoE"] = "BoE Mob Drop: Zufällige Bosse und Mobs in SSC/TK."
L["BT/HYJALBoP"] = "BoP Mob Drop: Zufällige Bosse und Mobs in Hyjal/BT."
L["HYJALBoP"] = "BoP Mob Drop: Zufällige Bosse in Hyjal."
L["SunwellBoP"] = "BoP Mob Drop: Zufällige Bosse and Mobs im Sonnenbrunnenplateau."
L["SunwellBoE"] = "BoE Mob Drop: Zufällige Bosse and Mobs im Sonnenbrunnenplateau."
L["BT/HYJALBoE"] = "BoE Mob Drop: Zufällige Bosse und Mobs in Hyjal/BT."
L["ZA"] = "BoP Mob Drop: Zufällige Bosse in Zul'Aman"
L["Unknown"] = "Der Droport dieses Rezepts ist unbekannt."

-- Faction info
L["WintersVeil"] = "Winterhauchfest"
L["Lunar Festival"] = "Mondfest"
L["Seasonal"] = "Saisonbedingt"

-- Alchemy Obtain Information
L["Discovery - Flasks/Potions"] = "Entdeckung: Fläschchen, Elixiere oder Tränke, die Kräuter aus der Scherbenwelt benötigen."
L["Discovery - Protection Potions"] = "Entdeckung: Erhebliche Schutztränke."
L["Discovery - Transmutes"] = "Entdeckung: Transmutationen, die Material aus der Scherbenwelt benötigen."
L["Goblin Rocket Fuel Obt"] = "Hergestellt: Dieses Rezept kann von Gobliningenieuren hergestellt werden"
L["Gurubashi Mojo Madness Obt"] = "Kann an einer Schrifttafel am Rande des Wahnsinns gelernt werden, ZG"
L["Mighty Trolls Blood Potion Obt"] = "Rede mit Henry Stern im Hügel der Klingenhauer"
-- Mob Drop
L["Elixir of Greater Firepower Obt"] = "BoE Mob Drop: Wachmann, Zuchtmeister und Sklavenhändler der Dunkeleisenzwerge, Sengende Schlucht"
L["Elixir of the Mongoose Obt"] = "BoE Mob Drop: Jadefeuerschurke, Teufelswald, Schurke der Legashi, Azshara"
L["Elixir of the Sages Obt"] = "BoE Mob Drop: Scharlachroter Erzmagier, Scharlachroter Kleriker, ÖPL"
L["Fel Mana Potion Obt"] = "BoP Mob Drop: Chevalier, Blutritter, Soldat, Erzmagier, Blutwärter, Zenturio und Zauberbinder der Mondfinsternis, Schattenmondtal"
L["Fel Regeneration Potion Obt"] = "BoP Mob Drop: Wächter, Wichtel, Tüftler und Schmied der Todesschmiede, Schattenmondtal"
L["Fel Strength Elixir Obt"] = "BoP Mob Drop: Waffenschmied der Mo'arg, Schreckensmeister, Schreckensmeister und Hexenmeister des Schattenrats, Schattenmondtal"
L["Gift of Arthas Obt"] = "BoE Mob Drop: Sabbernder Guhl, Skelettschinder, WPL"
L["Greater Arcane Protection Potion Obt"] = "BoE Mob Drop: Kobaltblauer Magiewirker, Winterquell"
L["Greater Fire Protection Potion Obt"] = "BoE Mob Drop: Herbeirufer und Pyromant der Feuerbrand, LBRS"
L["Greater Frost Protection Potion Obt"] = "BoE Mob Drop: Frosthagelriese, Winterquell"
L["Greater Nature Protection Potion Obt"] = "BoE Mob Drop: Verfallender Schrecken, Faulendes Ungetüm, WPL"
L["Greater Shadow Protection Potion Obt"] = "BoE Mob Drop: Dunkler Adept, Schattenmagier, ÖPL"
L["Major Arcane Protection Potion Obt"] = "BoP Mob Drop: Arkanist der Vir'aani, Nagrand"
L["Major Fire Protection Potion Obt"] = "BoP Mob Drop: Astromagier der Sonnensucher, Die Mechanar"
L["Major Frost Protection Potion Obt"] = "BoP Mob Drop: Nexusprinz Shaffar, Managruft"
L["Major Holy Protection Potion Obt"] = "BoP Mob Drop: Abyssischer Flammenbringer, Schergrat"
L["Major Shadow Protection Potion Obt"] = "BoP Mob Drop: Hexenmeister des Schattenrats, Schattenmondtal"
L["Mighty Rage Potion Obt"] = "BoE Mob Drop: Töter des Schwarzfels, Brennende Steppe"
L["Wildvine Potion Obt"] = "BoE Mob Drop: Trolle im Hinterland und Schlingendorntal"
-- Quest
L["Discolored Healing Potion Obt"] = "Wilde Herzen"
L["Elixir of Brute Force Obt"] = "Blutblütensprösslinge bei Dadanga im Krater von Un'Goro abgeben.\n      Seit 2.0 beim Lehrer lernbar"
L["Lesser Stoneshield Potion Obt"] = "Flüssigstein"
L["Restorative Potion Obt"] = "Reagenzien-Suche im Ödland II (Elite, Uldaman)"


-- Beast Training Obtain Information
L["Rare"] = true
L["Elite"] = true
-- Beasts which have training skills
L["Agam'ar"] = true
L["Aku'mai Fisher"] = true
L["Aku'mai Snapjaw"] = true
L["Angerclaw Mauler"] = true
L["Arash-ethis"] = true
L["Ashenvale Bear"] = true
L["Ashmane Boar"] = true
L["Barbed Crustacean"] = true
L["Barnabus"] = true
L["Battleboar"] = true
L["Bellygrub"] = true
L["Besseleth"] = true
L["Bhag'thera"] = true
L["Bjarn"] = true
L["Black Bear Patriarch"] = true
L["Black Ravager Mastiff"] = true
L["Black Ravager"] = true
L["Blackrock Worg"] = true
L["Blackwind Warp Chaser"] = true
L["Blisterpaw Hyena"] = true
L["Bloodaxe Worg"] = true
L["Bloodfalcon"] = true
L["Bloodmaul Battle Worg"] = true
L["Bloodmaul Dire Wolf"] = true
L["Bloodsnout Worg"] = true
L["Bonepaw Hyena"] = true
L["Bristleback Battleboar"] = true
L["Broken Tooth"] = true
L["Carrion Vulture"] = true
L["Cave Creeper"] = true
L["Chatter"] = true
L["Clack the Reaver"] = true
L["Clattering Crawler"] = true
L["Cleft Scorpid"] = true
L["Cloud Serpent"] = true
L["Cobalt Serpent"] = true
L["Coilskar Cobra"] = true
L["Corrupted Mottled Boar"] = true
L["Corrupted Scorpid"] = true
L["Coyote Packleader"] = true
L["Coyote"] = true
L["Crag Boar"] = true
L["Crag Coyote"] = true
L["Crag Stalker"] = true
L["Crazed Dragonhawk"] = true
L["Creepthess"] = true
L["Dark Screecher"] = true
L["Dark Worg"] = true
L["Darkfang Creeper"] = true
L["Deadly Cleft Scorpid"] = true
L["Deadmire"] = true
L["Death Flayer"] = true
L["Death Howl"] = true
L["Deathlash Scorpid"] = true
L["Deathstrike Tarantula"] = true
L["Deep Stinger"] = true
L["Deepmoss Creeper"] = true
L["Deepmoss Webspinner"] = true
L["Den Mother"] = true
L["Deviate Adder"] = true
L["Deviate Coiler Hatchling"] = true
L["Deviate Coiler"] = true
L["Deviate Crocolisk"] = true
L["Deviate Dreadfang"] = true
L["Deviate Moccasin"] = true
L["Deviate Stinglash"] = true
L["Deviate Venomwing"] = true
L["Deviate Viper"] = true
L["Dire Mottled Boar"] = true
L["Diseased Grizzly"] = true
L["Diseased Wolf"] = true
L["Dread Flyer"] = true
L["Dread Ripper"] = true
L["Dreadfang Lurker"] = true
L["Dreadfang Widow"] = true
L["Dreadmaw Crocolisk"] = true
L["Drywallow Crocolisk"] = true
L["Drywallow Daggermaw"] = true
L["Drywallow Snapper"] = true
L["Durotar Tiger"] = true
L["Eclipsion Dragonhawk"] = true
L["Elder Ashenvale Bear"] = true
L["Elder Cloud Serpent"] = true
L["Elder Crag Boar"] = true
L["Elder Crag Coyote"] = true
L["Elder Mistvale Gorilla"] = true
L["Elder Moss Creeper"] = true
L["Elder Mottled Boar"] = true
L["Elder Mountain Boar"] = true
L["Elder Plainstrider"] = true
L["Elder Shadowmaw Panther"] = true
L["Elder Shardtooth"] = true
L["Elder Springpaw"] = true
L["Encrusted Surf Crawler"] = true
L["Enraged Ravager"] = true
L["Felpaw Ravager"] = true
L["Felpaw Wolf"] = true
L["Felsworn Scalewing"] = true
L["Feral Crag Coyote"] = true
L["Feral Dragonhawk Hatchling"] = true
L["Feral Mountain Lion"] = true
L["Ferocious Grizzled Bear"] = true
L["Fire Roc"] = true
L["Firetail Scorpid"] = true
L["Flatland Cougar"] = true
L["Fleeting Plainstrider"] = true
L["Forest Lurker"] = true
L["Forest Moss Creeper"] = true
L["Forest Spider"] = true
L["Foreststrider Fledgling"] = true
L["Frostsaber Cub"] = true
L["Frostsaber Huntress"] = true
L["Frostsaber Stalker"] = true
L["Ghamoo-ra"] = true
L["Ghost Saber"] = true
L["Ghostclaw Lynx"] = true
L["Ghostclaw Ravager"] = true
L["Ghostpaw Alpha"] = true
L["Ghostpaw Runner"] = true
L["Giant Foreststrider"] = true
L["Giant Moss Creeper"] = true
L["Giant Plains Creeper"] = true
L["Giant Webwood Spider"] = true
L["Giant Wetlands Crocolisk"] = true
L["Githyiss the Vile"] = true
L["Goretusk"] = true
L["Gray Bear"] = true
L["Gray Forest Wolf"] = true
L["Great Goretusk"] = true
L["Greater Duskbat"] = true
L["Greater Firebird"] = true
L["Greater Fleshripper"] = true
L["Greater Kraul Bat"] = true
L["Greater Tarantula"] = true
L["Greater Thunderhawk"] = true
L["Greater Windroc"] = true
L["Green Recluse"] = true
L["Groddoc Thunderer"] = true
L["Grovestalker Lynx "] = true
L["Grunter"] = true
L["Gutripper"] = true
L["Hakkar'i Frostwing"] = true
L["Hakkar'i Sapper"] = true
L["Ice Claw Bear"] = true
L["Ironback"] = true
L["Ironbeak Hunter"] = true
L["Ironbeak Owl"] = true
L["Ironbeak Screecher"] = true
L["Ironfur Bear"] = true
L["Ironfur Patriarch"] = true
L["Jaguero Stalker"] = true
L["Jungle Thunderer"] = true
L["Juvenile Snow Leopard"] = true
L["Kaliri Matriarch"] = true
L["Kaliri Swooper"] = true
L["King Bangalash"] = true
L["Kraul Bat"] = true
L["Krellack"] = true
L["Kresh"] = true
L["Kurzen War Tiger"] = true
L["Lady Sathrah"] = true
L["Large Crag Boar"] = true
L["Large Loch Crocolisk"] = true
L["Leech Widow"] = true
L["Loch Crocolisk"] = true
L["Longsnout"] = true
L["Longtooth Howler"] = true
L["Longtooth Runner"] = true
L["Lost Torranche"] = true
L["Lupos"] = true
L["Magram Bonepaw"] = true
L["Male Kaliri Hatchling"] = true
L["Mangeclaw"] = true
L["Mangy Mountain Boar"] = true
L["Mazzranache"] = true
L["Mesa Buzzard"] = true
L["Mist Howler"] = true
L["Mistvale Gorilla"] = true
L["Mongress"] = true
L["Monstrous Crawler"] = true
L["Monstrous Plaguebat"] = true
L["Moonstalker Runt"] = true
L["Moonstalker Sire"] = true
L["Mottled Boar"] = true
L["Mottled Drywallow Crocolisk"] = true
L["Mountain Boar"] = true
L["Mountain Lion"] = true
L["Mudrock Snapjaw"] = true
L["Murk Slitherer"] = true
L["Murk Spitter"] = true
L["Naraxis"] = true
L["Night Web Matriarch"] = true
L["Night Web Spider"] = true
L["Nightsaber"] = true
L["Noxious Plaguebat"] = true
L["Oasis Snapjaw"] = true
L["Ol' Sooty"] = true
L["Old Cliff Jumper"] = true
L["Old Grizzlegut"] = true
L["Olm the Wise"] = true
L["Ornery Plainstrider"] = true
L["Panther"] = true
L["Phoenix-Hawk Hatchling"] = true
L["Plague Lurker"] = true
L["Plaguebat"] = true
L["Plagued Swine"] = true
L["Plains Creeper"] = true
L["Porcine Entourage"] = true
L["Prairie Stalker"] = true
L["Prairie Wolf Alpha"] = true
L["Prairie Wolf"] = true
L["Princess"] = true
L["Prowler"] = true
L["Pygmy Surf Crawler"] = true
L["Quillfang Ravager"] = true
L["Quillfang Skitterer"] = true
L["Rabid Blisterpaw"] = true
L["Rabid Crag Coyote"] = true
L["Ragged Scavenger"] = true
L["Raging Agam'ar"] = true
L["Rak'Shiri"] = true
L["Ravage"] = true
L["Ravager Specimen"] = true
L["Ravenous Windroc"] = true
L["Razorfang Hatchling"] = true
L["Razzashi Adder"] = true
L["Razzashi Cobra"] = true
L["Razzashi Serpent"] = true
L["Rekk'tilac"] = true
L["Rema"] = true
L["Ridge Huntress"] = true
L["Ridge Stalker Patriarch"] = true
L["Ridge Stalker"] = true
L["Rip-Blade Ravager"] = true
L["Ripfang Lynx"] = true
L["Ripscale"] = true
L["Roc"] = true
L["Rockhide Boar"] = true
L["Rogue Vale Screecher"] = true
L["Rotting Agam'ar"] = true
L["Salt Flats Vulture"] = true
L["Saltwater Snapjaw"] = true
L["Sandfury Guardian"] = true
L["Sarkoth"] = true
L["Savannah Patriarch"] = true
L["Sawtooth Snapper"] = true
L["Scalewing Serpent"] = true
L["Scarlet Tracking Hound"] = true
L["Scarred Crag Boar"] = true
L["Scarshield Worg"] = true
L["Scorchshell Pincer"] = true
L["Scorpashi Lasher"] = true
L["Scorpashi Snapper"] = true
L["Scorpashi Venomlash"] = true
L["Scorpid Bonecrawler"] = true
L["Scorpid Duneburrower"] = true
L["Scorpid Dunestalker"] = true
L["Scorpid Hunter"] = true
L["Scorpid Reaver"] = true
L["Scorpid Tail Lasher"] = true
L["Scorpid Terror"] = true
L["Scorpid Worker"] = true
L["Scorpok Stinger"] = true
L["Searing Roc"] = true
L["Shadow Panther"] = true
L["Shadowmaw Panther"] = true
L["Shadowwing Owl"] = true
L["Shanda the Spinner"] = true
L["Shardtooth Bear"] = true
L["Shore Crawler"] = true
L["Shrike Bat"] = true
L["Silithid Creeper"] = true
L["Silithid Swarmer"] = true
L["Silt Crawler"] = true
L["Silvermane Howler"] = true
L["Silvermane Stalker"] = true
L["Silvermane Wolf"] = true
L["Sin'Dall"] = true
L["Skettis Kaliri"] = true
L["Skittering Crustacean"] = true
L["Small Crag Boar"] = true
L["Snapjaw"] = true
L["Snapping Crustacean"] = true
L["Snarler"] = true
L["Snow Tracker Wolf"] = true
L["Son of Hakkar"] = true
L["Soulflayer"] = true
L["Sparkleshell Snapper"] = true
L["Spawn of Hakkar"] = true
L["Spiteflayer"] = true
L["Spot"] = true
L["Starving Blisterpaw"] = true
L["Starving Mountain Lion"] = true
L["Starving Winter Wolf"] = true
L["Stonelash Flayer"] = true
L["Stonelash Pincer"] = true
L["Stonelash Scorpid"] = true
L["Stonetusk Boar"] = true
L["Stranglethorn Tiger"] = true
L["Strigid Hunter"] = true
L["Strigid Owl"] = true
L["Swamp Jaguar"] = true
L["Swiftwing Shredder"] = true
L["Tarantula"] = true
L["Thistle Bear"] = true
L["Thistle Boar"] = true
L["Thornfang Ravager"] = true
L["Thornfang Venomspitter"] = true
L["Thunderhawk Cloudscraper"] = true
L["Thunderhawk Hatchling"] = true
L["Tide Crawler"] = true
L["Timber Worg"] = true
L["Timber"] = true
L["Timberweb Recluse"] = true
L["Twilight Runner"] = true
L["U'cha"] = true
L["Uhk'loc"] = true
L["Un'Goro Thunderer"] = true
L["Vale Screecher"] = true
L["Venomlash Scorpid"] = true
L["Venomous Cloud Serpent"] = true
L["Venomtail Scorpid"] = true
L["Venomtip Scorpid"] = true
L["Vicious Night Web Spider"] = true
L["Vile Sting"] = true
L["Vilebranch Raiding Wolf"] = true
L["Warp Chaser"] = true
L["Warp Hunter"] = true
L["Warp Stalker"] = true
L["Washte Pawne"] = true
L["Wayward Buzzard"] = true
L["Webwood Silkspinner"] = true
L["Webwood Venomfang"] = true
L["Wildthorn Lurker"] = true
L["Windroc Hunter"] = true
L["Windroc Huntress"] = true
L["Windroc Matriarch"] = true
L["Windroc"] = true
L["Winter Wolf"] = true
L["Winterspring Owl"] = true
L["Winterspring Screecher"] = true
L["Wood Lurker"] = true
L["Worg"] = true
L["Young Forest Bear"] = true
L["Young Goretusk"] = true
L["Young Mesa Buzzard"] = true
L["Young Panther"] = true
L["Young Stranglethorn Tiger"] = true
L["Young Thistle Boar"] = true
L["Zaricotl"] = true
L["Zulian Panther"] = true
L["Zulian Stalker"] = true

-- Blacksmithin Obtain Information
L["Annihilator Obt"] = "BoE Mob Drop: Rüstmeister Zigris, LBRS"
L["Arcanite Champion Obt"] = "BoE Mob Drop: Goraluk Hammerbruch, UBRS"
L["Arcanite Reaper Obt"] = "BoE Mob Drop: Bannok Grimmaxt, LBRS"
L["Barbaric Iron Boots Obt"] = "Questbelohnung (H): In den Boden getrampelt"
L["Barbaric Iron Breastplate Obt"] = "Questbelohnung (H): Barbarische Waffenschmiedekunst"
L["Barbaric Iron Gloves Obt"] = "Questbelohnung (H): Freude der Omoshs"
L["Barbaric Iron Helm Obt"] = "Questbelohnung (H): Hörner der Raserei"
L["Barbaric Iron Shoulders Obt"] = "Questbelohnung (H): Über Eisenschulterstücke"
L["Black Grasp of the Destroyer Obt"] = "BoP Mob Drop: Moam, AQ20"
L["Blacksmithing Plans"] = "Item Drop: Zufallsdropps aus Plänen in BRT und Stratholme"
L["Blazing Rapier Obt"] = "Questbelohnung: Verderbnis"
L["Dark Iron Plate Obt"] = "BoE Mob Drop: Ribbly Schraubstutz, BRT"
L["Dark Iron Pulverizer Obt"] = "BoE Mob Drop: Grizzle, BRT"
L["Dark Iron Sunderer Obt"] = "BoE Mob Drop: Betrunkener Gast, Ribblys Spießgeselle, BRT"
L["Dawn's Edge Obt"] = "Questbelohnung: Schlangenstein der Schattenjägerin"
L["Demon Forged Breastplate Obt"] = "Questbelohnung: Die Dämonenschmiede"
L["Earthpeace Breastplate Obt"] = "BoP Mob Drop, Hochbotaniker Freywinn, Die Botanika"
L["Enchanted Battlehammer Obt"] = "Questbelohnung: Süße Beschaulichkeit"
L["Enchanted Thorium Breastplate Obt"] = "Questbelohnung: Verzauberter Thoriumplattenpanzer: Band I"
L["Enchanted Thorium Helm Obt"] = "Questbelohnung: Verzauberter Thoriumplattenpanzer: Band III"
L["Enchanted Thorium Leggings Obt"] = "Questbelohnung: Verzauberter Thoriumplattenpanzer: Band II"
L["Felsteel Gloves Obt"] = "BoP Mob Drop: Mönch der Auchenai, Auchenaikrypta"
L["Felsteel Helm Obt"] = "BoP Mob Drop: Fanatiker der Kabale, Schattenlabyrinth"
L["Felsteel Leggings Obt"] = "BoP Mob Drop: Entfesselter Verdammnisbringer, Die Arkatraz"
L["Fiery Plate Gauntlets Obt"] = "Questbelohnung: Feurige Plattenstulpen"
L["Frostguard Obt"] = "BoE Mob Drop: Großknecht Marcrid, WPL"
L["Golden Scale Gauntlets Obt"] = "Questbelohnung (A): Die Herkunft der Schmiedekunst"
L["Greater Ward of Shielding Obt"] = "BoP Mob Drop: Blutwärter des Sonnenzorns, Nethersturm"
L["Hammer of the Titans Obt"] = "BoE Mob Drop: Maleki der Leichenblasse, Stratholme"
L["Heartseeker Obt"] = "BoE Mob Drop: Kanonenmeister Willey, Stratholme"
L["Heavy Copper Longsword Obt"] = "Questbelohnung (A): Nachschub für die Front (neu)"
L["Imperial Plate Belt Obt"] = "Questbelohnung: Imperialer Plattengürtel"
L["Imperial Plate Boots Obt"] = "Questbelohnung: Imperiale Plattenstiefel"
L["Imperial Plate Bracers Obt"] = "Questbelohnung: Imperiale Plattenarmschienen"
L["Imperial Plate Chest Obt"] = "Questbelohnung: Imperiale Plattenrüstung"
L["Imperial Plate Helm Obt"] = "Questbelohnung: Imperialer Plattenhelm"
L["Imperial Plate Leggings Obt"] = "Questbelohnung: Imperiale Plattengamaschen"
L["Imperial Plate Shoulders Obt"] = "Questbelohnung: Imperiale Plattenschultern"
L["Inlaid Mithril Cylinder Obt"] = "Hergestellt: Das Rezept kann von Gnomeningieuren hergestellt werden."
L["Invulnerable Mail Obt"] = "BoE Mob Drop: Goraluk Hammerbruch, UBRS"
L["Ironforge Breastplate Obt"] = "Questbelohnung (A): Die Aufrüstung im Rotkammgebirge"
L["Khorium Belt Obt"] = "BoP Mob Drop: Räuber der Finsterblut, Nagrand"
L["Khorium Boots Obt"] = "BoP Mob Drop: Körperloser Beschützer, Nethersturm"
L["Khorium Pants Obt"] = "BoP Mob Drop: Wächter der Todesschmiedes, Schattenmondtal"
L["Masterwork Stormhammer Obt"] = "BoE Mob Drop: Goraluk Hammerbruch, UBRS"
L["Orcish War Leggings Obt"] = "Questbelohnung (H): Die alten Traditionen"
L["Ornate Mithril Gloves Obt"] = "Questbelohnung: Der große silberne Betrüger"
L["Ornate Mithril Helm Obt"] = "Questbelohnung: Ein schlauer Kopf auf den Schultern"
L["Ornate Mithril Pants Obt"] = "Questbelohnung: Hier verhütten, da verhütten"
L["Ornate Mithril Shoulder Obt"] = "Questbelohnung: Die Kunst der Magieerfüllung"
L["Ragesteel Breastplate Obt"] = "BoP Mob Drop, Krieger der Aschenzungen, Schattenmondtal"
L["Ragesteel Gloves Obt"] = "BoP Mob Drop: Krieger der Felsfäuste, Nagrand"
L["Ragesteel Helm Obt"] = "BoP Mob Drop: Grollwaches, Schergrat"
L["Ragesteel Shoulders Obt"] = "BoP Mob Drop: Wütender Erdgeist, Wütender Luftgeist, Wütender Feuergeist, Wütender Wassergeist, Schattenmondtal"
L["Runic Breastplate Obt"] = "BoE Mob Drop: Strashazmyrmidone, Düstermarschen (Alcaz Insel)"
L["Runic Plate Boots Obt"] = "BoE Mob Drop: Scharlachroter Chevalier, WPL"
L["Runic Plate Helm Obt"] = "BoE Mob Drop: Strashazkrieger, Düstermarschen (Alcaz Insel)"
L["Runic Plate Leggings Obt"] = "BoE Mob Drop: Scharlachroter Schmied, WPL"
L["Runic Plate Shoulders Obt"] = "BoE Mob Drop: Strashazschlangenwache, Düstermarschen (Alcaz Insel)"
L["Sulfuron Hammer Obt"] = "Questbelohnung: Ein verbindlicher Vertrag"
L["Swiftsteel Gloves Obt"] = "BoP Mob Drop, Nexuswandler, Managruft"
L["Thick Obsidian Breastplate Obt"] = "BoP Mob Drop: Der Prophet Skeram, AQ40"
L["Volcanic Hammer Obt"] = "BoE Mob Drop: Volchan (Rar), Brennende Steppe"

-- Cooking Obtain Information
L["Fishing Daily"] = "Questbelohnung: Zufällige Belohnung von der täglichen Angelquest."
L["Cooking Daily"] = "Questbelohnung: Zufällige Belohnung von der täglichen Kochquest."
L["Goldthorn Tea Obt"] = "Rede mit Henry Stern im Hügel der Klingenhauer"
L["Stewed Trout Obt"] = "Lehrer: Kylene"
-- Mob Drop
L["Runn Tum Tuber Surprise Obt"] = "Pusillin"
L["Savory Deviate Delight Obt"] = "Seltener World Drop: Brachland"
-- Quest
L["Barbecued Buzzard Wing Obt"] = "Gegrillte Bussardflügel"
L["Beer Basted Boar Ribs Obt"] = "Eberrippchen in Biersauce"
L["Big Bear Steak Obt"] = "Die Rettung"
L["Blood Sausage Obt"] = "Blutwurst aus Thelsamar"
L["Buzzard Bites Obt"] = "Questbelohnung: So weich wie Butter"
L["Crocolisk Gumbo Obt"] = "Lehrlingspflichten"
L["Crocolisk Steak Obt"] = "Krokiliskenjagd"
L["Crunchy Serpent Obt"] = "Leckerbissen der Mok'Nathal"
L["Crunchy Spider Surprise Obt"] = "Knusperkost"
L["Curiously Tasty Omelet Obt"] = "Ormers Rache"
L["Dig Rat Stew Obt"] = "Grubenratteneintopf"
L["Dirge's Kickin' Chimaerok Chops Obt"] = "Dirges abgefahrene Chimaerokkoteletts"
L["Gooey Spider Cake Obt"] = "Schwärzliche Krebsküchlein"
L["Goretusk Liver Pie Obt"] = "Pastete aus Geiferzahnleber"
L["Hot Lion Chops Obt"] = "Elixier der Schmerzen"
L["Kaldorei Spider Kabob Obt"] = "Rezept der Kaldorei"
L["Murloc Fin Soup Obt"] = "Fischhandel"
L["Redridge Goulash Obt"] = "Rotkammgulasch"
L["Roasted Moongraze Tenderloin Obt"] = "Die große Mondweidenjagd"
L["Seasoned Wolf Kabob Obt"] = "Gewürzter Wolfskebab"
L["Smoked Desert Dumplings Obt"] = "Wüstenrezept"
L["Soothing Turtle Bisque Obt"] = "Milde Schildkrötensuppe"
L["Strider Stew Obt"] = "Schreitereintopf"
L["Tasty Lion Steak Obt"] = "Teure Bedrohung"
L["Thistle Tea Ally Obt"] = "Klavens Turm"
L["Thistle Tea Horde Obt"] = "Mission: möglich, aber nicht sehr wahrscheinlich"
L["Westfall Stew Obt"] = "Westfalleintopf"

-- Enchanting Obtain Information
L["Enchant 2H Weapon - Major Agility Obt"] = "Todesbringer der Eredar"
L["Enchant 2H Weapon - Major Intellect Obt"] = "Purpurroter Zauberhexer"
L["Enchant 2H Weapon - Major Spirit Obt"] = "Adept aus Scholomance"
L["Enchant 2H Weapon - Savagery Obt"] = "Zenturio der Zerschmetterten Hand"
L["Enchant 2H Weapon - Superior Impact Obt"] = "Elitesoldat der Schwarzfaustlegion"
L["Enchant Boots - Dexterity Obt"] = "Tobendes Skelett"
L["Enchant Boots - Fortitude Obt"] = "Astraler Priester"
L["Enchant Boots - Surefooted Obt"] = "Phantombühnenarbeiter"
L["Enchant Bracer - Fortitude Obt"] = "Orakel des Echsenkessels"
L["Enchant Bracer - Major Defense Obt"] = "Auslöscher des Astraleums"
L["Enchant Bracer - Spellpower Obt"] = "Geomant der Blutschläger"
L["Enchant Bracer - Superior Strength Obt"] = "Hexenmeister der Totenwindoger"
L["Enchant Cloak - Greater Arcane Resistance Obt"] = "Erzmagier der Mondfinsternis"
L["Enchant Cloak - Greater Shadow Resistance Obt"] = "Leerkreischer"
L["Enchant Cloak - Lesser Agility Obt"] = "Auftragsmörder des Syndikats"
L["Enchant Cloak - Lesser Agility Obt1"] = "Auftragsmörder der Wüstenläufer, Gesetzloser der Wüstenläufer"
L["Enchant Gloves - Advanced Herbalism Obt"] = "Morastlord, Moosbart, Sumpfwandler, Sumpfwandlerältester, Wuchernder Schrecken"
L["Enchant Gloves - Advanced Mining Obt"] = "Akkordminenarbeiter der Venture Co."
L["Enchant Gloves - Fishing Obt"] = "Narbenflosse, Küstenläufer der Fetzenflossen, Orakel der Fetzenflossen, Matschkrabbler der Fetzenflossen, Gezeitenjäger der Fetzenflossen"
L["Enchant Gloves - Herbalism Obt"] = "Wahnsinniges Urtum, Welkes Urtum"
L["Enchant Gloves - Herbalism Obt1"] = "Rachsüchtiges Urtum, Geschwärztes Urtum, Verkohltes Urtum"
L["Enchant Gloves - Mining Obt"] = "Dunkeleisenzwerg, Demolierer der Dunkeleisenzwerge, Tunnelgräber der Dunkeleisenzwerge, Saboteur der Dunkeleisenzwerge, Balgaras der Niederträchtige"
L["Enchant Gloves - Skinning Obt"] = "Nimar der Töter, Berserker der Bleichborken, Kopfjäger der Bleichborken, Schattenjäger der Bleichborken"
L["Enchant Weapon - Crusader Obt"] = "Scharlachroter Zauberbinder"
L["Enchant Weapon - Deathfrost Obt"] = "Lord Ahune - Sonnenwendfest"
L["Enchant Weapon - Fiery Weapon Obt"] = "Pyromant Weisenkorn"
L["Enchant Weapon - Icy Chill Obt"] = "Gepeinigter Hochgeborener"
L["Enchant Weapon - Lifestealing Obt"] = "Spektraler Forscher"
L["Enchant Weapon - Major Intellect Obt"] = "Forscher des Sonnenzorns"
L["Enchant Weapon - Major Spellpower Obt"] = "Zauberdieb von Bash'ir"
L["Enchant Weapon - Superior Striking Obt"] = "Kriegsherr der Felsspitzoger"
L["Enchant Weapon - Unholy Weapon Obt"] = "Thuzadinschattenzauberer"
L["Smoking Heart of the Mountain Obt"] = "Lord Roccor"

-- Engineering Obtain Information
L["ENG_MEMBERSHIP_BENEFITS"] = "Zufällige Questbelohnung: Mitgliedskarten-Erneuerung, Tanaris"
L["Adamantite Arrow Maker Obt"] = "BoP Mob Drop: Bogenschütze des Sonnenzorns, Nethersturm"
L["Alarm-O-Bot Obt"] = "BoE Mob Drop: Waffentechniker, BRT"
L["Arcanite Dragonling Obt"] = "BoE Mob Drop: Kobaltblauer Magiewirker, Winterquell"
L["Dark Iron Bomb Obt"] = "BoE Mob Drop: Waffentechniker, BRT"
L["Dark Iron Rifle Obt"] = "BoE Mob Drop: Schicksalsträchtiger Handwerker, BRT"
L["Discombobulator Ray Obt"] = "Benutze DELTA-Daten-Sicherheitszugangskarte im Matrix Punchograph 3005-D in Gnomeregan.\n    - BoE Mob Drop: Robogenieur Thermadraht, Gnomeregan"
L["Felsteel Boomstick Obt"] = "BoP Mob Drop: Ingenieur der Schicksalsschmiede, Schergrat"
L["Field Repair Bot 110G Obt"] = "BoP Mob Drop: Analysator der Gan'arg, Schergrat"
L["Field Repair Bot 74A Obt"] = "Klickbare Rolle neben Golemlord Argelmach, BRT"
L["Flame Detector Obt"] = "BoE Mob Drop: Robogenieur Thermadraht, Gnomeregan"
L["Flash Bomb Obt"] = "Questbelohnung: Perlentauchen (danach Quest Blitzstrahlbombenanleitung für Ingenieure)"
L["Flawless Arcanite Rifle Obt"] = "BoE Mob Drop: Schattenjäger der Moosschinder, ÖPL"
L["Goblin Jumper Cables XL Obt"] = "BoE Mob Drop: Stöpsel Zapfring, BRT"
L["Hyper-Radiant Flame Reflector Pbt"] = "BoE Mob Drop: Solakar Feuerkrone, UBRS"
L["Hyper-Vision Goggles Obt"] = "BoP Mob Drop: Waffenschmied der Mo'arg, Schattenmondtal"
L["Khorium Scope Obt"] = "BoP Mob Drop: Jagdschütze des Sonnenzorns, Nethersturm"
L["Major Recombobulator Obt"] = "Düsterbruch Nord Tribute Run, Kiste"
L["Minor Recombobulator Obt"] = "Benutze die Weiße Lochkarte im Matrix Punchograph 3005-A, danach die Gelbe Lochkarte im Matrix Punchograph 3005-B in Gnomeregan."
L["Rocket Boots Xtreme Lite Obt"] = "BoP Mob Drop: Mechanolord Kapazitus, Die Mechanar"
L["Rocket Boots Xtreme Obt"] = "BoP Mob Drop: Robogenieur Dampfhammer, Die Dampfkammer"
L["Stabilized Eternium Scope Obt"] = "BoP Mob Drop: Attumen der Jäger, Karazhan"
L["Steam Tonk Controller Obt"] = "Questbelohnung: 40 Gewinnlose - Bauplan: Dampfpanzersteuerung (Dunkelmond-Jahrmarkt)"
L["Ultra-Flash Shadow Reflector Obt"] = "BoE Mob Drop: Purpurroter Inquisitor, Stratholme"
L["Voice Amplification Modulator Obt"] = "BoE Mob Drop: Purpurroter Inquisitor, Stratholme"
L["World Enlarger Obt"] = "BoE Mob Drop: Waffentechniker, BRT"
L["Zapthrottle Mote Extractor Obt"] = "Questbelohnung: Der schockdrosselnde Partikelextraktor!"

-- First Aid Obtain Information
-- Nothing here needed yet

-- Jewelcrafting Obtain Information
L["Arcane Khorium Band Obt"] = "BoP Mob Drop: Magiertöter, Nethersturm"
L["Blades Edge Summon Bosses"] = "BoP Mob Drop: Verschieden Elitebosse im Schergrat"
L["Chaotic Skyfire Diamond Obt"] = "BoP Mob Drop: Sirene der Echsennarbe, Schattenmondtal"
L["Circlet of Arcane Might Obt"] = "BoP Mob Drop: Epochenjäger, Vorgebirge des Alten Hügellands"
L["Coronet of the Verdant Flame Obt"] = "BoP Mob Drop: Botaniker der Sonnensucher, Die Botanika"
L["Dark Iron Scorpid Obt"] = "BoP Mob Drop: Golemlord Argelmach, BRT"
L["Figurine - Black Diamond Crab Obt"] = "BoP Mob Drop: Rüstmeister Zigris, UBRS"
L["Khorium Band of Frost Obt"] = "BoP Mob Drop: Zauberhexerin des Echsenkessels, Die Dampfkammer"
L["Khorium Band of Leaves Obt"] = "BoP Mob Drop: Schreckensfalke der Vekh'nir, Schergrat"
L["Khorium Band of Shadows Obt"] = "BoP Mob Drop: Schattenbeschwörer des Dunklen Rats, Schattenmondtal"
L["Khorium Inferno Band Obt"] = "BoP Mob Drop: Dunkelwirker Syth, Sethekkhallen"

-- Leatheworking Obtain Information
L["Arcane Armor Kit Obt"] = "BoP Mob Drop: Chronolord Deja, Der schwarze Morast"
L["Bag of Many Hides Obt"] = "BoP Mob Drop: Oger, Hügelwand (nordwestlich oberhalb von Shattrath)"
L["Black Dragonscale Leggings Obt"] = "BoE Mob Drop: Hauptmann der Zorneshämmer, BRT"
L["Black Dragonscale Shoulders Obt"] = "BoE Mob Drop: Hauptmann der Zorneshämmer, BRT"
L["Blue Dragonscale Shoulders Obt"] = "BoE Mob Drop: Klippenbrecher, Azshara"
L["Deviate Scale Belt Obt"] = "Questbelohnung: Ausrottung der Deviat"
L["Devilsaur Leggings Obt"] = "BoE Mob Drop: Geklonter Brühschlammer, Dickflüssiger Brühschlammer, Krater von Un'Goro"
L["Flame Armor Kit Obt"] = "BoP Mob Drop: Riesengroßer Abyss, Die Arkatraz"
L["Frost Armor Kit Obt"] = "BoP Mob Drop: Wasserbeschwörerin Thespia, Die Dampfkammer"
L["Frostsaber Gloves Obt"] = "BoE Mob Drop: Totemiker der Winterfelle, Winterquell"
L["Frostsaber Leggings Obt"] = "BoE Mob Drop: Höhlenbehüter der Winterfelle, Winterquell"
L["Frostsaber Tunic Obt"] = "BoE Mob Drop: Ursa der Winterfelle, Winterquell"
L["Green Dragonscale Leggings Obt"] = "BoE Mob Drop: Düsterwurm, Versunkener Tempel"
L["Heavy Scorpid Leggings Obt"] = "BoE Mob Drop: Töter des Schwarzfels, Brennende Steppe"
L["Heavy Scorpid Shoulders Obt"] = "BoE Mob Drop: Kampfmeister des Schwarzfels, Brennende Steppe"
L["Heavy Scorpid Vest Obt"] = "BoE Mob Drop: Portalsucher, Verwüstete Lande"
L["Ironfeather Breastplate Obt"] = "BoE Mob Drop: Balgabzieher der Blutfratzen, Hinterland"
L["Kodo Hide Bag Obt"] = "Questbelohnung(H): Kodobalgtasche"
L["Living Breastplate Obt"] = "BoE Mob Drop: Verfallender Schrecken, WPL"
L["Living Leggings Obt"] = "BoE Mob Drop: Schamane der Totenwaldfelle, Teufelswald"
L["Moonglow Vest Obt"] = "Questbelohnung(A): Mondscheinweste"
L["Nature Armor Kit Obt"] = "BoP Mob Drop: Mennu der Verräter, Die Sklavenunterkünfte"
L["Onyxia Scale Cloak Obt"] = "Questbelohnung: Onyxias Kopf besorgen, in Sturmwind/Orgrimmar abgeben, danach lernt man es"
L["Red Dragonscale Breastplate Obt"] = "BoP Mob Drop: General Drakkisath, UBRS"
L["Runic Leather Armor Obt"] = "BoE Mob Drop: Dunkler Beschwörer aus Scholomance, Scholomance"
L["Runic Leather Bracers Obt"] = "BoE Mob Drop: Kultist von Jaedenar, Teufelswald"
L["Runic Leather Shoulders Obt"] = "BoE Mob Drop: Purpurroter Kampfmagier, Stratholme"
L["Shadow Armor Kit Obt"] = "BoP Mob Drop: Zeitverlorener Schattenmagier, Sethekkhallen"
L["Stormshroud Armor Obt"] = "BoE Mob Drop: Arkkoranorakel, Azshara"
L["Stormshroud Gloves Obt"] = "BoE Mob Drop: Der Windhäscher, Silithus, Prinzessin Tempestria, Winterquell"
L["Stormshroud Shoulders Obt"] = "BoE Mob Drop: Arkkorocs Sohn, Azshara"
L["Stylin' Adventure Hat Obt"] = "BoP Mob Drop: Scharfschütze von Durnholde, Vorgebirge des Alten Hügellands"
L["Stylin' Crimson Hat Obt"] = "BoP Mob Drop: Rabenwächter der Sethekk, Sethekkhallen"
L["Stylin' Jungle Hat Obt"] = "BoP Mob Drop: Bewahrerin der Zeitrisse, Bewahrerin der Zeitrisse, Der schwarze Morast"
L["Stylin' Purple Hat Obt"] = "BoP Mob Drop: Schwarzherz der Hetzer, Schattenlabyrinth"
L["Tough Scorpid Boots Obt"] = "BoE Mob Drop: Schurke der Wüstenläufer, Tanaris"
L["Tough Scorpid Bracers Obt"] = "BoE Mob Drop: Schattenmagier der Wüstenläufer, Tanaris"
L["Tough Scorpid Breastplate Obt"] = "BoE Mob Drop: Bandit der Wüstenläufer, Tanaris"
L["Tough Scorpid Gloves Obt"] = "BoE Mob Drop: Dieb der Wüstenläufer, Tanaris"
L["Tough Scorpid Helm Obt"] = "BoE Mob Drop: Andre Feuerbart, Gesetzloser der Wüstenläufer, Tanaris"
L["Tough Scorpid Leggings Obt"] = "BoE Mob Drop: Schurke der Wüstenläufer, Tanaris"
L["Tough Scorpid Shoulders Obt"] = "BoE Mob Drop: Andre Feuerbart, Gesetzloser der Wüstenläufer, Tanaris"
L["Volcanic Breastplate Obt"] = "BoE Mob Drop: Grunzer der Feuerbrand, LBRS"
L["Volcanic Leggings Obt"] = "BoE Mob Drop: Schläger der Feuermägen, Brennende Steppe"
L["Volcanic Shoulders Obt"] = "BoE Mob Drop: Legionär der Feuerbrand, LBRS"
L["Wicked Leather Armor Obt"] = "BoE Mob Drop: Spektraler Forscher, Scholomance"
L["Wicked Leather Belt Obt"] = "BoE Mob Drop: Tobsüchtiger Ghul, Stratholme"
L["Wicked Leather Bracers Obt"] = "BoE Mob Drop: Schurke der Legashi, Azshara"
L["Wicked Leather Headband Obt"] = "BoE Mob Drop: Jadefeuerschwindler, Teufelswald"
L["Wild Leather Boots Obt"] = "Questbelohnung: Wildlederstiefel"
L["Wild Leather Cloak Obt"] = "Questbelohnung: Meister des Wildleders"
L["Wild Leather Helmet Obt"] = "Questbelohnung: Wildlederhelm"
L["Wild Leather Leggings Obt"] = "Questbelohnung: Wildledergamaschen"
L["Wild Leather Shoulders Obt"] = "Questbelohnung: Wildlederschultern"
L["Wild Leather Vest Obt"] = "Questbelohnung: Wildlederweste"

-- Smelting Obtain Information
L["Dark Iron Obt"] = "Questbelohnung: BRT. Benötigt 2 Sternrubine, 20 Gold- und 10 Echtsilberbarren. Rede mit Dunk'rel."
L["Elementium Obt"] = "Gedankenkontrolle Krixix in BWL. In der Begleiterleiste ist ein Zauber, den man sich selbst oder anderen Spielern beibringen kann."

-- Rogue Poison Obtain Information
-- Nothing here needed yet

-- Tailoring Obtain Information
L["Arcanoweave Boots Obt"] = "Astromagier der Sonnensucher"
L["Arcanoweave Bracers Obt"] = "Schildwache der Arkatraz"
L["Black Silk Pack Obt"] = "Spion des Syndikats"
L["Black Silk Pack Obt1"] = "Spitzel von Theramore"
L["Black Silk Pack Obt2"] = "Schattenhafter Auftragsmörder"
L["Cindercloth Cloak Obt"] = "Thaurissanischer Feuerwandler"
L["Cindercloth Gloves Obt"] = "Feuerwache des Schattenhammers"
L["Cindercloth Pants Obt"] = "Thaurissanischer Feuerwandler"
L["Cindercloth Vest Obt"] = "Feuerwache des Schattenhammers"
L["Cloak of Fire Obt"] = "Übermeister Pyron"
L["Felcloth Bag Obt"] = "Aus Buch neben Jandice Barov lernbar"
L["Ghostweave Belt Obt"] = "Verweilender Hochgeborener"
L["Ghostweave Gloves Obt"] = "Verweilender Hochgeborener"
L["Ghostweave Gloves Obt1"] = "Ungesehener Diener"
L["Ghostweave Pants Obt"] = "Spektraler Bürger"
L["Ghostweave Vest Obt"] = "Ungesehener Diener"
L["Mooncloth Boots Obt"] = "Hochheiliger Stoff"
L["Robe of the Archmage Obt"] = "Pyromant der Feuerbrand"
L["Robe of Winter Night Obt"] = "Kobaltblauer Magiewirker"
L["Robes of Arcana Obt"] = "Leerruferin des dunklen Strangs"
L["Robes of Arcana Obt1"] = "Verzauberer der Defias"
L["Shadoweave Mask Obt"] = "Questbelohnung: Der Untermarkt"
L["Soulcloth Shoulders Obt"] = "Phantomknecht"
L["Soulcloth Vest Obt"] = "Phantomdiener"
L["Wizardweave Leggings Obt"] = "Dunkler Beschwörer"
L["Wizardweave Robe Obt"] = "Dunkler Zauberer"
L["Wizardweave Turban Obt"] = "Dunkler Zauberer"

-- Vendor Names
L["Aaron Hollman"] = "Aaron Hollmann"
L["Abigail Shiel"] = "Abigail Shiel"
L["Aged Dalaran Wizard"] = "Gealterter Hexer von Dalaran"
L["Alchemist Gribble"] = "Alchimist Grabbel"
L["Alchemist Pestlezugg"] = "Alchimist Stößelbruch"
L["Aldraan"] = "Aldraan"
L["Alexandra Bolero"] = "Alexandra Bolero"
L["Algernon"] = "Algernon"
L["Altaa"] = "Altaa"
L["Amy Davenport"] = "Amy Davenport"
L["Andrew Hilbert"] = "Andrew Hilbert"
L["Andrion Darkspinner"] = "Andrion Dunkelweber"
L["Androd Fadran"] = "Androd Fadran"
L["Apothecary Antonivich"] = "Apotheker Antonivich"
L["Aresella"] = "Aresella"
L["Arras"] = "Arras"
L["Arred"] = "Arred"
L["Arrond"] = "Arrond"
L["Asarnan"] = "Asarnan"
L["Balai Lok'Wein"] = "Balai Lok'Wein"
L["Bale"] = "Bale"
L["Banalash"] = "Banalash"
L["Blimo Gadgetspring"] = "Blimo Federdings"
L["Blixrez Goodstitch"] = "Blixrez Gutstich"
L["Blizrik Buckshot"] = "Blizrik Bockschuss"
L["Bliztik"] = "Bliztik"
L["Bombus Finespindle"] = "Bombus Feinspindel"
L["Borto"] = "Borto"
L["Borya"] = "Borya"
L["Brienna Starglow"] = "Brienna Sternenglanz"
L["Bro'kin"] = "Bro'kin"
L["Bronk"] = "Bronk"
L["Burbik Gearspanner"] = "Burbik Ritzelspann"
L["Burko"] = "Burko"
L["Captured Gnome"] = "Gefangener Gnom"
L["Catherine Leland"] = "Catherine Leland"
L["Christoph Jeffcoat"] = "Christoph Jeffkott"
L["Clyde Ranthal"] = "Clyde Ranthal"
L["Constance Brisboise"] = "Constance Brisboise"
L["Cookie McWeaksauce"] = "Kräcka Aschebäscha"
L["Cookie One-Eye"] = "Kräcka Einauge"
L["Coreiel"] = "Coreiel"
L["Corporal Bluth"] = "Korporal Bluth"
L["Cowardly Crosby"] = "Feiger Crosby"
L["Crazk Sparks"] = "Crazk Funks"
L["Cro Threadstrong"] = "Cro Dickfädel"
L["Daga Ramba"] = "Daga Ramba"
L["Daggle Ironshaper"] = "Daggle Eisenformer"
L["Dalria"] = "Dalria"
L["Daniel Bartlett"] = "Daniel Bartlett"
L["Danielle Zipstitch"] = "Danielle Stichelnaht"
L["Darian Singh"] = "Darian Singh"
L["Darnall"] = "Darnall"
L["Dealer Malij"] = "Händler Malij"
L["Defias Profiteer"] = "Schieber der Defias"
L["Deneb Walker"] = "Deneb Wandler"
L["Derak Nightfall"] = "Derak Nachtlauer"
L["Deynna"] = "Deynna"
L["Dirge Quikcleave"] = "Dirge Schnetzelhack"
L["Doba"] = "Doba"
L["Drac Roughcut"] = "Drac Grobschnitt"
L["Drake Lindgren"] = "Drake Lindgren"
L["Drovnar Strongbrew"] = "Drovnar Starkbräu"
L["Edna Mullby"] = "Edna Mullby"
L["Egomis"] = "Egomis"
L["Eiin"] = "Eiin"
L["Elynna"] = "Elynna"
L["Emrul Riknussun"] = "Emrul Riknussun"
L["Eriden"] = "Eriden"
L["Erika Tate"] = "Erika Tate"
L["Erilia"] = "Erilia"
L["Feera"] = "Feera"
L["Felannia"] = "Felannia"
L["Felicia Doan"] = "Felicia Doan"
L["Felika"] = "Felika"
L["Fradd Swiftgear"] = "Fradd Schnellschalt"
L["Fyldan"] = "Fyldan"
L["Gagsprocket"] = "Quietschspross"
L["Gambarinka"] = "Gambarinka"
L["Gearcutter Cogspinner"] = "Ritzelschnitt Zahnrad"
L["Gelanthis"] = "Gelanthis"
L["George Candarte"] = "George Candarte"
L["Gharash"] = "Gharash"
L["Ghok'kah"] = "Ghok'kah"
L["Gidge Spellweaver"] = "Gidge Spruchwirker"
L["Gigget Zipcoil"] = "Gigget Reißspule"
L["Gikkix"] = "Gikkix"
L["Gina MacGregor"] = "Gina MacGregor"
L["Gloria Femmel"] = "Gloria Femmel"
L["Glyx Brewright"] = "Glyx Gutbräu"
L["Gnaz Blunderflame"] = "Gnaz Dusselflamm"
L["Gretta Ganter"] = "Gretta Ganter"
L["Grimtak"] = "Grimtak"
L["Haalrun"] = "Haalrun"
L["Haferet"] = "Haferet"
L["Hagrus"] = "Hagrus"
L["Hammon Karwn"] = "Hammon Karwn"
L["Harggan"] = "Harggan"
L["Harklan Moongrove"] = "Harklan Mondhain"
L["Harlown Darkweave"] = "Harlown Dunkelwirker"
L["Harn Longcast"] = "Harn Rutenwurf"
L["Heldan Galesong"] = "Heldan Sturmgesang"
L["Helenia Olden"] = "Helenia Olden"
L["Himmik"] = "Himmik"
L["Hula'mahi"] = "Hula'mahi"
L["Innkeeper Biribi"] = "Gastwirtin Biribi"
L["Innkeeper Fizzgrimble"] = "Gastwirt Zischgrimbel"
L["Innkeeper Grilka"] = "Gastwirtin Grilka"
L["Jabbey"] = "Stupser"
L["Jandia"] = "Jandia"
L["Janet Hommers"] = "Janet Hommers"
L["Jangdor Swiftstrider"] = "Jangdor Flinkschreiter"
L["Jannos Ironwill"] = "Jannos Eisenwill"
L["Jaquilina Dramet"] = "Jaquilina Dramet"
L["Jase Farlane"] = "Jase Langweg"
L["Jazzrik"] = "Jazzrik"
L["Jeeda"] = "Jeeda"
L["Jennabink Powerseam"] = "Jennabink Starksaum"
L["Jessara Cordell"] = "Jessara Cordell"
L["Jim Saltit"] = "Jim Salzit"
L["Jinky Twizzlefixxit"] = "Jinky Pfuschelfix"
L["Johan Barnes"] = "Johan Barnes"
L["Joseph Moore"] = "Joseph Moor"
L["Jubie Gadgetspring"] = "Jubie Federdings"
L["Jun'ha"] = "Jun'ha"
L["Juno Dufrain"] = "Juno Dufrain"
L["Jutak"] = "Jutak"
L["Kaita Deepforge"] = "Kaita Tiefenschmied"
L["Kalaen"] = "Kalaen"
L["Kalldan Felmoon"] = "Kalldan Teufelsmond"
L["Kania"] = "Kania"
L["Keena"] = "Keena"
L["Kelsey Yance"] = "Kelsey Yance"
L["Kendor Kabonka"] = "Kendor Kabonka"
L["Khara Deepwater"] = "Khara Tiefenwasser"
L["Kiknikle"] = "Kiknikle"
L["Killian Sanatha"] = "Killian Sanatha"
L["Kilxx"] = "Kilxx"
L["Kireena"] = "Kireena"
L["Kithas"] = "Kithas"
L["Knaz Blunderflame"] = "Knaz Dusselflamm"
L["Kor'geld"] = "Kor'geld"
L["Krek Cragcrush"] = "Krek Schmetterfels"
L["Kriggon Talsone"] = "Kriggon Talsone"
L["Krinkle Goodsteel"] = "Krinkle Goldstahl"
L["Kulwia"] = "Kulwia"
L["Kzixx"] = "Kzixx"
L["Laird"] = "Laird"
L["Landraelanis"] = "Landraelanis"
L["Lardan"] = "Lardan"
L["Lebowski"] = "Lebowski"
L["Leeli Longhaggle"] = "Leeli Langfeilsch"
L["Leo Sarn"] = "Leo Sarn"
L["Leonard Porter"] = "Leonard Porter"
L["Lilly"] = "Lilly"
L["Lindea Rabonne"] = "Lindea Rabonne"
L["Lizbeth Cromwell"] = "Lizbeth Kromwell"
L["Logannas"] = "Logannas"
L["Loolruna"] = "Loolruna"
L["Lorelae Wintersong"] = "Lorelae Winterklang"
L["Lyna"] = "Lyna"
L["Madame Ruby"] = "Madame Rubin"
L["Mahu"] = "Mahu"
L["Mallen Swain"] = "Mallen Knab"
L["Malygen"] = "Malygen"
L["Mari Stonehand"] = "Mari Steinhand"
L["Maria Lumere"] = "Maria Lumere"
L["Martine Tramblay"] = "Martine Tramblei"
L["Masat T'andr"] = "Masat T'andr"
L["Master Chef Mouldier"] = "Meisterkoch Mouldier"
L["Mathar G'ochar"] = "Mathar G'ochar"
L["Mavralyn"] = "Mavralyn"
L["Mazk Snipeshot"] = "Mazk Zielschuss"
L["Melaris"] = "Melaris"
L["Micha Yance"] = "Micha Yance"
L["Millie Gregorian"] = "Millie Gregorian"
L["Mishta"] = "Mishta"
L["Mixie Farshot"] = "Mixie Weitschuss"
L["Montarr"] = "Montarr"
L["Muheru the Weaver"] = "Muheru der Weber"
L["Muuran"] = "Muuran"
L["Mythrin'dir"] = "Mythrin'dir"
L["Naal Mistrunner"] = "Naal Nebelläufer"
L["Namdo Bizzfizzle"] = "Namdo Blitzzischel"
L["Nandar Branson"] = "Nandar Branson"
L["Narkk"] = "Narkk"
L["Nasmara Moonsong"] = "Nasmara Mondweise"
L["Nata Dawnstrider"] = "Nata Morgenwandler"
L["Neal Allen"] = "Neal Allen"
L["Neii"] = "Neii"
L["Nergal"] = "Nergal"
L["Nerrist"] = "Nerrist"
L["Nessa Shadowsong"] = "Nessa Schattensang"
L["Nina Lightbrew"] = "Nina Brauleicht"
L["Nioma"] = "Nioma"
L["Nula the Butcher"] = "Nula die Metzgerin"
L["Nyoma"] = "Nyoma"
L["Ogg'marr"] = "Ogg'marr"
L["Otho Moji'ko"] = "Otho Moji'ko"
L["Outfitter Eric"] = "Ausstatter Eric"
L["Phea"] = "Phea"
L["Plugger Spazzring"] = "Stöpsel Zapfring"
L["Pratt McGrubben"] = "Pratt McGrubben"
L["Qia"] = "Qia"
L["Quartermaster Davian Vaclav"] = "Rüstmeister Davian Watzlav"
L["Quartermaster Jaffrey Noreliqe"] = "Rüstmeister Jaffrey Keinespuhr"
L["Quelis"] = "Quelis"
L["Ranik"] = "Ranik"
L["Rann Flamespinner"] = "Rann Flammenweber"
L["Rartar"] = "Rartar"
L["Rathis Tomber"] = "Rathis Tomber"
L["Rikqiz"] = "Rikqiz"
L["Rizz Loosebolt"] = "Rizz Wackelbolz"
L["Rohok"] = "Rohok"
L["Ronald Burch"] = "Ronald Burch"
L["Rungor"] = "Rungor"
L["Ruppo Zipcoil"] = "Ruppo Reißspule"
L["Saenorion"] = "Saenorion"
L["Seer Janidi"] = "Seherin Janidi"
L["Sewa Mistrunner"] = "Sewa Nebelläufer"
L["Shadi Mistrunner"] = "Shadi Nebelläufer"
L["Shankys"] = "Shankys"
L["Sheendra Tallgrass"] = "Sheendra Hochschilf"
L["Shen'dralar Provisioner"] = "Versorger der Shen'dralar"
L["Sheri Zipstitch"] = "Sheri Stichelnaht"
L["Sid Limbardi"] = "Sid Limbardi"
L["Skreah"] = "Skreah"
L["Soolie Berryfizz"] = "Soolie Brausefitz"
L["Sovik"] = "Sovik"
L["Stuart Fleming"] = "Stuart Fleming"
L["Sumi"] = "Sumi"
L["Super-Seller 680"] = "Superverkaufomat 680"
L["Supply Officer Mills"] = "Versorgungsoffizier Mühlens"
L["Tamar"] = "Tamar"
L["Tansy Puddlefizz"] = "Tansy Pfützplatsch"
L["Tarban Hearthgrain"] = "Tarban Kornbäcker"
L["Tari'qa"] = "Tari'qa"
L["Tatiana"] = "Tatiana"
L["Thaddeus Webb"] = "Thaddeus Webner"
L["Tharynn Bouden"] = "Tharynn Bouden"
L["Thomas Yance"] = "Thomas Yance"
L["Tilli Thistlefuzz"] = "Tilli Distelflaum"
L["Truk Wildbeard"] = "Truk Wildbart"
L["Tunkk"] = "Tunkk"
L["Ulthaan"] = "Ulthaan"
L["Ulthir"] = "Ulthir"
L["Uriku"] = "Uriku"
L["Uthok"] = "Uthok"
L["Vaean"] = "Vaean"
L["Valdaron"] = "Valdaron"
L["Veenix"] = "Veenix"
L["Vendor-Tron 1000"] = "Kaufotron 1000"
L["Vharr"] = "Vharr"
L["Viggz Shinesparked"] = "Viggz Funkenschimmer"
L["Vivianna"] = "Vivianna"
L["Vizzklick"] = "Vizzklick"
L["Vodesiin"] = "Vodesiin"
L["Wenna Silkbeard"] = "Wenna Seidenbart"
L["Werg Thickblade"] = "Werg Breitklinge"
L["Wik'Tar"] = "Wik'Tar"
L["Wind Trader Lathrai"] = "Windhändler Lathrai"
L["Wrahk"] = "Wrahk"
L["Wulan"] = "Wulan"
L["Wunna Darkmane"] = "Wunna Dunkelmähne"
L["Xandar Goodbeard"] = "Xandar Gutbart"
L["Xen'to"] = "Xen'to"
L["Xizk Goodstitch"] = "Xizk Gutstich"
L["Xizzer Fizzbolt"] = "Xizzer Zischbolz"
L["Yatheon"] = "Yatheon"
L["Yonada"] = "Yonada"
L["Yuka Screwspigot"] = "Yuka Schraubstutz"
L["Yurial Soulwater"] = "Yurial Seelenwasser"
L["Zan Shivsproket"] = "Zan Messerritzel"
L["Zannok Hidepiercer"] = "Zannok Ledernaht"
L["Zansoa"] = "Zansoa"
L["Zaralda"] = "Zaralda"
L["Zarena Cromwind"] = "Zarena Stahlwind"
L["Zixil"] = "Zixil"
L["Zorbin Fandazzle"] = "Zorbin von Schiller"
L["Zurai"] = "Zurai"
L["Narj Deepslice"] = "Narj Schnitzelschnitt"
L["Fazu"] = "Fazu"
L["Zargh"] = "Zargh"
L["Smudge Thunderwood"] = "Smudge Donnerholz"
L["Sassa Weldwell"] = "Sassa Nahtgut"
