local L = AceLibrary("AceLocale-2.2"):new("QuestsFu")

L:RegisterTranslations("frFR", function() return {
	["(done)"] = "(termin\195\169e)",
	["(failed)"] = "(\195\169chec)",

	TOOLTIP_HINT = "|cffeda55fClic|r pour ouvrir le journal de qu\195\170tes. |cffeda55fMaj-Clic|r pour ins\195\169rer la qu\195\170tre dans la discussion. |cffeda55fMaj-Ctrl-Clic|r pour ins\195\169rer les objectifs dans la discussion. |cffeda55fAlt-Clic|r pour ajouter la qu\195\170te à la zone de suivi.",
	["Show"] = "Afficher",
	["Choose what information to display"] = "Choisit les informations à afficher",
	["Text"] = "Texte",
	["Toolbar text"] = "Texte dans la barre d'\195\169tat",
	["Current"] = "Actuelles",
	["Show current # of quests"] = "Affiche le nombre de qu\195\170tes",
	["Completed"] = "Termin\195\169es",
	["Show # of quests completed"] = "Affiche le nombre de qu\195\170tes termin\195\169es",
	["Total"] = "Total",
	["Show total possible quests"] = "Affiche le nombre total de qu\195\170tes que vous pouvez prendre",
	["Last message"] = "Dernier message",
	["Show last quest status message"] = "Affiche le dernier message de qu\195\170te",
	["Levels"] = "Niveaux",
	["Show quest levels"] = "Affiche le niveau des qu\195\170tes",
--	["In Game"] = "En jeu",
--	["Show quest levels in the quest log and NPC dialogs"] = "Affiche le niveau des qu\195\170tes dans le journal de qu\195\170tes et les dialogues des PNJ",
	["In QuestsFu"] = "Dans QuestsFu",
	["Show quest levels in the QuestsFu tooltip"] = "Affiche le niveau des qu\195\170tes dans la tooltip de QuestsFu",
	["Zone"] = "Zone",
	["Show zone levels in the QuestsFu tooltip"] = "Afficher le niveaux des zones dans la tooltip de QuestsFu",
	["Impossible quests"] = "Qu\195\170tes impossibles",
	["Show impossible (red) quests"] = "Afficher les qu\195\170tes impossibles (rouges)",
	["Show quest zones"] = "Afficher les zones des qu\195\170tes",
	["Current area only"] = "Zone actuelle seulement",
	["Only show quests for the current zone"] = "Affiche uniquement les qu\195\170tes de la zone actuelle",
	["Class quests always"] = "Toujours afficher les qu\195\170tes de classe",
	["Always show class quests"] = "Affiche en permanence les qu\195\170tes de classe",
	["Details"] = "D\195\169tails",
	["Show quest details"] = "Afficher les d\195\169tails des qu\195\170tes",
	["Current area details only"] = "D\195\169tails pour la zone actuelle seulement",
	["Show details for current area quests only"] = "Affiche les d\195\169tails pour la zone actuelle uniquement",
	["Completed objectives"] = "Objectifs accomplis",
	["Show completed objectives"] = "Afficher les objectifs accomplis",
--	["Objectives in tooltip"] = "Objectifs dans la tooltip",
--	["Show quest objectives in item/mob tooltips"] = "Afficher les objectifs dans la tooltip des objets/monstres",
	["Objectives"] = "Objectifs",
	["Color objective completion status"] = "Coloriser le statut d'avancement des objectifs",
	["Wrap quest titles"] = "Couper les longs noms de qu\195\170te",
	["Wrap long quest titles on to multiple lines"] = "R\195\169partir les longs noms de qu\195\170tes sur plusieurs lignes",
--	["Use own tracker"] = "Zone de suivi am\195\169lior\195\169e",
--	["Replace the default quest tracker with a slightly more featureful one."] = "Remplace la zone de suivi par d\195\169faut par une autre plus compl\195\168te",
--	["Use own quest detail pane"] = "Fen\195\170tre de d\195\169tails am\195\169lior\195\169e",
--	["Display detailed quest information in a custom window."] = "Afficher les d\195\169tails des qu\195\170tes dans une fen\195\170tre am\195\169lior\195\169e",

	["Color zone names by suggested level"] = "Couleur des noms de zone suivant le niveau",
	["Color"] = "Couleur",
	["Color settings"] = "R\195\169glages des couleurs",
	["Title"] = "Nom de qu\195\170te",
	["Color the quest title by difficulty"] = "Coloriser le nom des qu\195\170tes selon la difficult\195\169",
	["Level"] = "Niveau",
	["Color the quest level by difficulty"] = "Coloriser le niveau des qu\195\170tes selon la difficult\195\169",

	--[[
	["bunch-of-directions"] = {
		"([^%a%d])(north)([^%a%d])",
		"([^%a%d])(northern)([^%a%d])",
		"([^%a%d])(west)([^%a%d])",
		"([^%a%d])(western)([^%a%d])",
		"([^%a%d])(east)([^%a%d])",
		"([^%a%d])(eastern)([^%a%d])",
		"([^%a%d])(south)([^%a%d])",
		"([^%a%d])(southern)([^%a%d])",
		"([^%a%d])(northwest)([^%a%d])",
		"([^%a%d])(northwestern)([^%a%d])",
		"([^%a%d])(northeast)([^%a%d])",
		"([^%a%d])(northeastern)([^%a%d])",
		"([^%a%d])(southwest)([^%a%d])",
		"([^%a%d])(southwestern)([^%a%d])",
		"([^%a%d])(southeast)([^%a%d])",
		"([^%a%d])(southeastern)([^%a%d])",
	}
	]]
} end)
