local L = AceLibrary("AceLocale-2.2"):new("QuestsFu")

L:RegisterTranslations("koKR", function() return {
	["(done)"] = "(완료)",
	["(failed)"] = "(실패)",

	["Toggle whether the %s module is active"] = "%s 모듈 사용을 전환합니다.",
	["Modules"] = "모듈",
	["Toggle whether the %s module is active"] = "%s 모듈 사용을 전환합니다.",

	["Strata"] = "프레임 레벨",
	["Adjust the strata of this panel (takes effect after you reload your UI)"] = "애드온의 프레임레벨을 변경합니다.(UI 재시작 후 적용됩니다.)",
	["Max height"] = "최대 높이",
	["Adjust the maximum height of this panel, in pixels (takes effect after you reload your UI)"] = "해당 패널의 최대 높이를 조절합니다. 픽셀 단위 (UI 재실행 후 변경됨)",
	["Minimum width"] = "최소 넓이",
	["Adjust the minimum width of this panel, in pixels (takes effect after you reload your UI)"] = "해당 패널의 최소 넓이를 조절합니다. 픽셀 단위 (UI 재실행 후 변경됨)",
	['BACKGROUND'] = "배경",
	['LOW'] = "낮음",
	['MEDIUM'] = "중간",
	['HIGH'] = "높음",

	["Lock"] = "잠금",
	["Lock or unlock this panel"] = "패널을 고정시키거나 이동시킵니다.",

	TOOLTIP_HINT = "퀘스트 로그를 열려면 |cffeda55f클릭|r하세요. 대화창에 퀘스트 정보를 입력하려면 |cffeda55fSHIFT-클릭|r하세요. 대화창에 목표 정보를 입력하려면 |cffeda55fSHIFT-CTRL-클릭|r하세요. 알림이에 추가하려면 |cffeda55fALT-클릭|r하세요.",
	["FuBar Tablet"] = "FuBar 패널",
	["Settings for the main FuBar tablet"] = "중요한 FuBar 패널을 위한 설정을 합니다.",
	["Show"] = "표시",
	["Choose what information to display"] = "표시할 정보를 선택합니다.",
	["Text"] = "텍스트",
	["Toolbar text"] = "툴바 텍스트",
	["Current"] = "현재",
	["Show current # of quests"] = "현재 퀘스트의 개수를 표시합니다.",
	["Completed"] = "완료",
	["Show # of quests completed"] = "완료된 퀘스트의 개수를 표시합니다.",
	["Total"] = "전체",
	["Show total possible quests"] = "수행 가능한 퀘스트의 총 개수를 표시합니다.",
	["Last message"] = "마지막 메시지",
	["Show last quest status message"] = "마지막 퀘스트 상태 메시지를 표시합니다.",
	["Levels"] = "레벨",
	["Show quest levels"] = "퀘스트 레벨을 표시합니다.",
	["In QuestsFu"] = "QuestsFu",
	["Show quest levels in the QuestsFu tooltip"] = "QuestsFu 툴팁에 퀘스트 레벨을 표시합니다.",
	["Zone"] = "지역",
	["Show zone levels in the QuestsFu tooltip"] = "QuestsFu 툴팁에 지역 레벨을 표시합니다.",
	["Impossible quests"] = "불가능한 퀘스트",
	["Show impossible (red) quests"] = "불가능한(붉은색) 퀘스트를 표시합니다.",
	["Show quest zones"] = "퀘스트 지역 표시",
	["Current area only"] = "현재 지역",
	["Only show quests for the current zone"] = "현재 지역 퀘스트만 표시합니다.",
	["Class quests always"] = "직업 퀘스트",
	["Always show class quests"] = "직업 퀘스트를 항상 표시합니다.",
	["Details"] = "내용",
	["Show quest details"] = "퀘스트 내용을 표시합니다.",
	["Current area details only"] = "현재 지역 내용",
	["Show details for current area quests only"] = "현재 지역 퀘스트만 내용을 표시합니다.",
	["Completed objectives"] = "완료된 목표",
	["Show completed objectives"] = "완료된 목표를 표시합니다.",
	["Objectives"] = "완료도 색상",
	["Color objective completion status"] = "완료 상태에 따른 목표 색상",
	["Wrap quest titles"] = "간략한 퀘스트",
	["Wrap long quest titles on to multiple lines"] = "긴 퀘스트 제목을 잛게 표시합니다.",

	["Color zone names by suggested level"] = "제안된 레벨별 지역 이름 색상",
	["Color"] = "색상",
	["Color settings"] = "색상 설정",
	["Title"] = "제목",
	["Color the quest title by difficulty"] = "난이도에 따른 퀘스트 제목 색상",
	["Level"] = "레벨",
	["Color the quest level by difficulty"] = "난이도에 따른 퀘스트 레벨 색상",

	["Colors"] = "색상",
	["Choose custom colors"] = "사용자 색상 선택",
	["Difficulty"] = "난이도",
	["Trivial"] = "쉬운",
	["Standard"] = "보통",
	["Difficult"] = "어려운",
	["Very difficult"] = "매우 어려운",
	["Impossible"] = "불가능",
	["Header"] = "제목",
	["Completion"] = "완료",
	["Not started"] = "시작하지 않음",
	["Underway"] = "수행중",
	["Done"] = "완료",
	["Other"] = "기타",
} end)
