BS_REQ_LEVEL = "需要宠物等级 ";
BS_LEVEL = "等级 ";
BS_NEXT_SUIT_LEVEL = "下一级(最适)";
BS_NEXT_LEVEL = "下一级";
BS_SUIT_LEVEL = "最适等级";
BS_DONT_EXIST = "不存在";
BS_UNLEARNT = "未学";
BS_LEARNT = "拥有";
BS_LEVEL_DESC = "(等级";
BS_ABILITY = "驯兽能力：";
BS_ABILITY_LORE = "驯兽能力：(.+)";
BS_BEAST_LORE = "野兽知识";
BS_BEAST = "野兽";
BS_LOAD_MESSAGE = "[野兽学识] by 互补古蓝  加载成功 ";
BS_TRAIN_LEVEL = "学习：等级 ";
BS_TRAIN_NOLEVEL = "|cffFF0000无可学等级|r";

if GetLocale() == "enUS" or GetLocale() == "enGB" then
BS_REQ_LEVEL = "Require Pet level";
BS_LEVEL = "Level ";
BS_NEXT_SUIT_LEVEL = "Next Level (Suitable)";
BS_NEXT_LEVEL = "Next Level";
BS_SUIT_LEVEL = "Suitable level";
BS_DONT_EXIST = "Doesn't exist";
BS_UNLEARNT = "Unlearnt";
BS_LEARNT = "Have";
BS_LEVEL_DESC = "(Level ";
BS_ABILITY = "Tamed Abilities: ";
BS_ABILITY_LORE = "Tamed Abilities:(.+)";
BS_BEAST_LORE = "Beast Lore";
BS_BEAST = "Beast";
BS_LOAD_MESSAGE = "[BeastSpell] by FaberiLan  successfully loaded";
BS_TRAIN_LEVEL = "Train: Level ";
BS_TRAIN_NOLEVEL = "|cffFF0000No trainable level|r";
end;