if GetLocale() == "enUS" or GetLocale() == "enGB" then

BST_List = {
 [1] = {"Arcane Resistance", "Fire Resistance", "Frost Resistance", "Nature Resistance", "Shadow Resistance", },
 [2] = {"Great Stamina", "Natural Armor", "Avoidance", "Cobra Reflexes", },
 [3] = {"Growl", "Cower", "Gore", "Claw", },
 [4] = {"Bite", "Dash", "Dive", "Screech", },
 [5] = {"Prowl", "Furious Howl", "Shell Shield", "Thunderstomp", "Scorpid Poison", },
 [6] = {"Charge", "Warp", "Fire Breath", "Poisonous Spit", "Lightning Breath", },
};
BST_Data = {
 --["Arcane Resistance"] = "Interface\\Icons\\Spell_Nature_StarFall"
 ["Arcane Resistance"] = {
  ["icon"] = "Spell_Nature_StarFall",
  ["max"] = 5,
  ["Lv"] = {20, 30, 40, 50, 60},
  ["TP"] = {5, 15, 45, 90, 105},
  ["til"] = "Passive",
  ["txt"] = {
   "Increase Arcane Resistance by 30.",
   "Increase Arcane Resistance by 60.",
   "Increase Arcane Resistance by 90.",
   "Increase Arcane Resistance by 120.",
   "Increase Arcane Resistance by 140.",
  },
 },
 ["Fire Resistance"] = {
  ["icon"] = "Spell_Fire_FireArmor",
  ["max"] = 5,
  ["Lv"] = {20, 30, 40, 50, 60},
  ["TP"] = {5, 15, 45, 90, 105},
  ["til"] = "Passive",
  ["txt"] = {
   "Increase Fire Resistance by 30.",
   "Increase Fire Resistance by 60.",
   "Increase Fire Resistance by 90.",
   "Increase Fire Resistance by 120.",
   "Increase Fire Resistance by 140.",
  },
 },
 ["Frost Resistance"] = {
  ["icon"] = "Spell_Frost_FrostWard",
  ["max"] = 5,
  ["Lv"] = {20, 30, 40, 50, 60},
  ["TP"] = {5, 15, 45, 90, 105},
  ["til"] = "Passive",
  ["txt"] = {
   "Increase Frost Resistance by 30.",
   "Increase Frost Resistance by 60.",
   "Increase Frost Resistance by 90.",
   "Increase Frost Resistance by 120.",
   "Increase Frost Resistance by 140.",
  },
 },
 ["Nature Resistance"] = {
  ["icon"] = "Spell_Nature_ResistNature",
  ["max"] = 5,
  ["Lv"] = {20, 30, 40, 50, 60},
  ["TP"] = {5, 15, 45, 90, 105},
  ["til"] = "Passive",
  ["txt"] = {
   "Increase Nature Resistance by 30.",
   "Increase Nature Resistance by 60.",
   "Increase Nature Resistance by 90.",
   "Increase Nature Resistance by 120.",
   "Increase Nature Resistance by 140.",
  },
 },
 ["Shadow Resistance"] = {
  ["icon"] = "Spell_Shadow_AntiShadow",
  ["max"] = 5,
  ["Lv"] = {20, 30, 40, 50, 60},
  ["TP"] = {5, 15, 45, 90, 105},
  ["til"] = "Passive",
  ["txt"] = {
   "Increase Shadow Resistance by 30.",
   "Increase Shadow Resistance by 60.",
   "Increase Shadow Resistance by 90.",
   "Increase Shadow Resistance by 120.",
   "Increase Shadow Resistance by 140.",
  },
 },

 ["Great Stamina"] = {
  ["icon"] = "Spell_Nature_UnyeildingStamina",
  ["max"] = 11,
  ["Lv"] = {10, 12, 18, 24, 30, 36, 42, 48, 54, 60, 70},
  ["TP"] = {5, 10, 15, 25, 50, 75, 100, 125, 150, 185, 215},
  ["til"] = "Passive",
  ["txt"] = {
   "Stamina increased by 3.",
   "Stamina increased by 5.",
   "Stamina increased by 7.",
   "Stamina increased by 10.",
   "Stamina increased by 13.",
   "Stamina increased by 17.",
   "Stamina increased by 21.",
   "Stamina increased by 26.",
   "Stamina increased by 32.",
   "Stamina increased by 40.",
   "Stamina increased by 64.",
  },
 },
 ["Natural Armor"] = {
  ["icon"] = "Spell_Nature_SpiritArmor",
  ["max"] = 11,
  ["Lv"] = {10, 12, 18, 24, 30, 36, 42, 48, 54, 60, 70},
  ["TP"] = {1, 5, 10, 15, 25, 50, 75, 100, 125, 150, 175},
  ["til"] = "Passive",
  ["txt"] = {
   "Armor increased by 50.",
   "Armor increased by 100",
   "Armor increased by 160.",
   "Armor increased by 240.",
   "Armor increased by 330.",
   "Armor increased by 430.",
   "Armor increased by 550.",
   "Armor increased by 675.",
   "Armor increased by 810.",
   "Armor increased by 1000.",
   "Armor increased by 1600.",
  },
 },
 ["Avoidance"] = {
  ["icon"] = "Spell_Magic_LesserInvisibilty",
  ["max"] = 2,
  ["Lv"] = {30, 60},
  ["TP"] = {15, 25},
  ["til"] = "Passive",
  ["txt"] = {
   "Reduces the damage your pet takes from AOE attacks by an additional 25%.",
   "Reduces the damage your pet takes from AOE attacks by an additional 50%.",
  },
 },
 ["Cobra Reflexes"] = {
  ["icon"] = "Spell_Nature_GuardianWard",
  ["max"] = 1,
  ["Lv"] = {30},
  ["TP"] = {15},
  ["til"] = "Passive",
  ["txt"] = {
   "Attack speed increased by 30%, but damage done is reduced."
  },
 },
 ["Growl"] = {
  ["icon"] = "Ability_Physical_Taunt",
  ["max"] = 8,
  ["Lv"] = {10, 10, 20, 30, 40, 50, 60, 70},
  ["TP"] = {0, 0, 0, 0, 0, 0, 0, 0},
  ["til"] = "15 Focus|5 sec cooldown",
  ["txt"] = {
   "Threat increase by 50, increasing the likelihood the creature will focus attacks on the pet.",
   "Threat increase by 65, increasing the likelihood the creature will focus attacks on the pet.",
   "Threat increase by 110, increasing the likelihood the creature will focus attacks on the pet.",
   "Threat increase by 170, increasing the likelihood the creature will focus attacks on the pet.",
   "Threat increase by 240, increasing the likelihood the creature will focus attacks on the pet.",
   "Threat increase by 320, increasing the likelihood the creature will focus attacks on the pet.",
   "Threat increase by 415, increasing the likelihood the creature will focus attacks on the pet.",
   "Threat increase by 664, increasing the likelihood the creature will focus attacks on the pet.",
  },
 },

 ["Bite"] = {
  ["icon"] = "Ability_Racial_Cannibalize",
  ["max"] = 9,
  ["Lv"] = {1, 8, 16, 24, 32, 40, 48, 56, 64},
  ["TP"] = {1, 4, 7, 10, 13, 17, 21, 25, 29},
  ["til"] = "35 Focus|10 sec. cooldown",
  ["txt"] = {
   "Causing 7-9 damage.",
   "Causing 16-18 damage.",
   "Causing 24-28 damage.",
   "Causing 31-37 damage.",
   "Causing 40-48 damage.",
   "Causing 49-59 damage.",
   "Causing 66-80 damage.",
   "Causing 81-99 damage.",
   "Causing 108-132 damage.",
  },
 },
 ["Claw"] = {
  ["icon"] = "Ability_Druid_Rake",
  ["max"] = 9,
  ["Lv"] = {1, 8, 16, 24, 32, 40, 48, 56, 64},
  ["TP"] = {1, 4, 7, 10, 13, 17, 21, 25, 29},
  ["til"] = "25 Focus|no cooldown",
  ["txt"] = {
   "Causing 4-6 damage.",
   "Causing 8-12 damage.",
   "Causing 12-16 damage.",
   "Causing 16-22 damage.",
   "Causing 21-29 damage.",
   "Causing 26-36 damage.",
   "Causing 35-49 damage.",
   "Causing 43-59 damage.",
   "Causing 54-76 damage.",
  },
 },

 ["Cower"] = {
  ["icon"] = "Ability_Druid_Cower",
  ["max"] = 7,
  ["Lv"] = {5, 15, 25, 35, 45, 55, 65},
  ["TP"] = {8, 10, 12, 14, 16, 18, 20},
  ["til"] = "25 Focus|5 sec cooldown",
  ["txt"] = {
   "Causing no damage but lowering your threat.",
  },
 },
 ["Dash"] = {
  ["icon"] = "Ability_Druid_Dash",
  ["max"] = 3,
  ["Lv"] = {30, 40, 50},
  ["TP"] = {15, 20, 25},
  ["til"] = "20 Focus|30 sec cooldown",
  ["txt"] = {
   "Increases movement speed by 40% for 15 sec.",
   "Increases movement speed by 60% for 15 sec.",
   "Increases movement speed by 80% for 15 sec.",
  },
 },
 ["Dive"] = {
  ["icon"] = "Spell_Shadow_BurningSpirit",
  ["max"] = 3,
  ["Lv"] = {30, 40, 50},
  ["TP"] = {15, 20, 25},
  ["til"] = "20 Focus|30 sec cooldown",
  ["txt"] = {
   "Increases movement speed by 40% for 15 sec.",
   "Increases movement speed by 60% for 15 sec.",
   "Increases movement speed by 80% for 15 sec.",
  },
 },
 ["Charge"] = {
  ["icon"] = "Ability_Hunter_Pet_Boar",
  ["max"] = 6,
  ["Lv"] = {1, 12, 24, 0, 48, 60},
  ["TP"] = {5, 10, 15, 0, 25, 29},
  ["til"] = "35 Focus|25 sec cooldown",
  ["txt"] = {
   "Immobilizes the target for 1 sec and adds 50 melee attack power to the boar's next attack.",
   "Immobilizes the target for 1 sec and adds 100 melee attack power to the boar's next attack.",
   "Immobilizes the target for 1 sec and adds 180 melee attack power to the boar's next attack.",
   "Immobilizes the target for 1 sec and adds ??? melee attack power to the boar's next attack.",
   "Immobilizes the target for 1 sec and adds 390 melee attack power to the boar's next attack.",
   "Immobilizes the target for 1 sec and adds 550 melee attack power to the boar's next attack.",
  },
 },
 ["Furious Howl"] = {
  ["icon"] = "Ability_Hunter_Pet_Wolf",
  ["max"] = 4,
  ["Lv"] = {10, 24, 40, 56},
  ["TP"] = {10, 15, 20, 25},
  ["til"] = "60 Focus|10 sec cooldown",
  ["txt"] = {
   "Party members within 15 yards receive an extra 9 to 11 damage to their next Physical attack.  Lasts 10 sec.",
   "Party members within 15 yards receive an extra 18 to 22 damage to their next Physical attack.  Lasts 10 sec.",
   "Party members within 15 yards receive an extra 28 to 34 damage to their next Physical attack.  Lasts 10 sec.",
   "Party members within 15 yards receive an extra 45 to 57 damage to their next Physical attack.  Lasts 10 sec.",
  },
 },
 ["Lightning Breath"] = {
  ["icon"] = "Spell_Nature_Lightning",
  ["max"] = 6,
  ["Lv"] = {1, 12, 24, 36, 48, 60},
  ["TP"] = {1, 5, 10, 15, 20, 25},
  ["til"] = "50 Focus",
  ["txt"] = {
   "Instantly dealing 11 to 13 Nature damage to a single target.",
   "Instantly dealing 21 to 23 Nature damage to a single target.",
   "Instantly dealing 36 to 40 Nature damage to a single target.",
   "Instantly dealing 51 to 59 Nature damage to a single target.",
   "Instantly dealing 78 to 90 Nature damage to a single target.",
   "Instantly dealing 99 to 113 Nature damage to a single target.",
  },
 },

 ["Prowl"] = {
  ["icon"] = "Ability_Druid_SupriseAttack",
  ["max"] = 3,
  ["Lv"] = {30, 40, 50},
  ["TP"] = {15, 20, 25},
  ["til"] = "40 Focus|10 sec cooldown",
  ["txt"] = {
   "Puts your pet in stealth mode, but slows its movement speed by 50%. The first attack from stealth receives a 20% bonus to damage.  Lasts until cancelled.",
   "Puts your pet in stealth mode, but slows its movement speed by 55%. The first attack from stealth receives a 35% bonus to damage.  Lasts until cancelled.",
   "Puts your pet in stealth mode, but slows its movement speed by 60%. The first attack from stealth receives a 50% bonus to damage.  Lasts until cancelled.",
  },
 },
 ["Scorpid Poison"] = {
  ["icon"] = "Ability_PoisonSting",
  ["max"] = 5,
  ["Lv"] = {8, 24, 40, 56, 64},
  ["TP"] = {10, 15, 20, 25, 29},
  ["til"] = "30 Focus|4 sec cooldown",
  ["txt"] = {
   "Inflicts 10 Nature damage over 10 sec, can stack up to 5 times.",
   "Inflicts 15 Nature damage over 10 sec, can stack up to 5 times.",
   "Inflicts 30 Nature damage over 10 sec, can stack up to 5 times.",
   "Inflicts 40 Nature damage over 10 sec, can stack up to 5 times.",
   "Inflicts 55 Nature damage over 10 sec, can stack up to 5 times.",
  },
 },
 ["Screech"] = {
  ["icon"] = "Ability_Hunter_Pet_Bat",
  ["max"] = 5,
  ["Lv"] = {8, 24, 48, 56, 64},
  ["TP"] = {10, 15, 20, 25, 29},
  ["til"] = "20 Focus|4 sec cooldown",
  ["txt"] = {
   "Blasts a single enemy for 7 to 9 damage and lowers the melee attack power of all enemies in melee range by 25. Lasts 4 sec.",
   "Blasts a single enemy for 12 to 16 damage and lowers the melee attack power of all enemies in melee range by 50. Lasts 4 sec.",
   "Blasts a single enemy for 19 to 25 damage and lowers the melee attack power of all enemies in melee range by 75. Lasts 4 sec.",
   "Blasts a single enemy for 26 to 46 damage and lowers the melee attack power of all enemies in melee range by 25. Lasts 4 sec.",
   "Blasts a single enemy for 33 to 61 damage and lowers the melee attack power of all enemies in melee range by 25. Lasts 4 sec.",
  },
 },
 
 ["Shell Shield"] = {
  ["icon"] = "Ability_Hunter_Pet_Turtle",
  ["max"] = 1,
  ["Lv"] = {15},
  ["TP"] = {20},
  ["til"] = "10 Focus|3 mins cooldown",
  ["txt"] = {
   "Damage taken reduced by 50%, increases the time between your pet's attacks by 43%, lasts 12 sec.",
  },
 },
 ["Thunderstomp"] = {
  ["icon"] = "Ability_Hunter_Pet_Gorilla",
  ["max"] = 3,
  ["Lv"] = {30, 40, 50},
  ["TP"] = {15, 20, 25},
  ["til"] = "60 Focus|1 mins cooldown",
  ["txt"] = {
   "Shakes the ground with thundering force, doing 67 to 77 Nature damage to all enemies within 8 yards.",
   "Shakes the ground with thundering force, doing 87 to 99 Nature damage to all enemies within 8 yards.",
   "Shakes the ground with thundering force, doing 115 to 133 Nature damage to all enemies within 8 yards.",
  },
 },

 --New abilities added in 2.0 and TBC
 ["Fire Breath"] = {
  ["icon"] = "Spell_Fire_Burnout",
  ["max"] = 2,
  ["Lv"] = {1, 60},
  ["TP"] = {5, 25},
  ["til"] = "50 Focus|10 sec cooldown",
  ["txt"] = {
   "Targets in a cone in front of the caster take 12-18 Fire damage over 2 sec.",
   "Targets in a cone in front of the caster take 111-123 Fire damage over 2 sec.",
  },
 },
 ["Gore"] = {
  ["icon"] = "INV_Weapon_Shortblade_28",
  ["max"] = 9,
  ["Lv"] = {1, 8, 16, 24, 0, 0, 48, 56, 63},
  ["TP"] = {1, 4, 7, 10, 13, 17, 21, 25, 29},
  ["til"] = "25 Focus",
  ["txt"] = {
   "Causing 3 to 5 damage. 50% chance to inflict double damage.",
   "Causing 6 to 10 damage. 50% chance to inflict double damage.",
   "Causing 9 to 13 damage. 50% chance to inflict double damage.",
   "Causing 12 to 18 damage. 50% chance to inflict double damage.",
   "Causing ?? to ?? damage. 50% chance to inflict double damage.",
   "Causing ?? to ?? damage. 50% chance to inflict double damage.",
   "Causing 24 to 40 damage. 50% chance to inflict double damage.",
   "Causing 30 to 48 damage. 50% chance to inflict double damage.",
   "Causing 37 to 61 damage. 50% chance to inflict double damage.",
  },
 },
 
 --need check
 ["Poisonous Spit"] = {
  ["icon"] = "Spell_Nature_CorrosiveBreath",
  ["max"] = 3,
  ["Lv"] = {15, 45, 60},
  ["TP"] = {5, 20, 25},
  ["til"] = "35 Focus|10 sec cooldown",
  ["txt"] = {
   "Spits out poison at target which causes 20 damage over 8 sec.",
   "Spits out poison at target which causes 72 damage over 8 sec.",
   "Spits out poison at target which causes 120 damage over 8 sec.",
  },
 },
 ["Warp"] = {
  ["icon"] = "Spell_Arcane_Arcane04",
  ["max"] = 1,
  ["Lv"] = {60},
  ["TP"] = {1},
  ["til"] = "25 Focus|15 sec cooldown",
  ["txt"] = {
   "Teleports to an enemy up to 30 yards away and gives the pet a 50% chance to avoid the next melee attack. Lasts 4 sec.",
  },
 },
};
BST_Species = {
 ["Bat"] = {"Bite", "Dive", "Screech"},
 ["Bear"] = {"Bite", "Claw"},
 ["Boar"] = {"Bite", "Charge", "Dash", "Gore"},
 ["Carrion Bird"] = {"Bite", "Claw", "Dive", "Screech"},
 ["Cat"] = {"Bite", "Claw", "Dash", "Prowl"},
 ["Crab"] = {"Claw"},
 ["Crocolisk"] = {"Bite"},
 ["Dragonhawk"] = {"Bite", "Dive", "Fire Breath"},
 ["Gorilla"] = {"Bite", "Thunderstomp"},
 ["Hyena"] = {"Bite", "Dash"},
 ["Nether Ray"] = {"Bite", "Dive"},
 ["Owl"] = {"Claw", "Dive", "Screech"},
 ["Raptor"] = {"Bite", "Claw", "Dash"},
 ["Ravager"] = {"Bite", "Gore", "Dash"},
 ["Scorpid"] = {"Claw", "Scorpid Poison"},
 ["Serpent"] = {"Bite", "Poisonous Spit"},
 ["Spider"] = {"Bite"},
 ["Spore Bat"] = {},
 ["Tallstrider"] = {"Bite", "Dash"},
 ["Turtle"] = {"Bite", "Shell Shield"},
 ["Warp Stalker"] = {"Bite", "Claw", "Warp"},
 ["Wind Serpent"] = {"Bite", "Dive", "Lightning Breath"},
 ["Wolf"] = {"Bite", "Dash", "Furious Howl"},
};
BST_Species2 = {
	"Arcane Resistance", "Fire Resistance", "Frost Resistance", "Nature Resistance", "Shadow Resistance",
	"Great Stamina", "Natural Armor", "Avoidance", "Cobra Reflexes", "Growl", "Cower",
};
end;