local L = AceLibrary("AceLocale-2.2"):new("XLoot")

L:RegisterTranslations("zhTW", function() 
	return {
		catSnap = "框架吸附設定",
		catLoot = "物品拾取設定",
		catFrame = "框架設定",
		catInfo = "拾取訊息",
		catGeneralAppearance = "一般表現",
		catFrameAppearance = "框架表現",
		catLootAppearance = "拾取物品表現",
		catExtras = "額外",

		["2.0 compatability"] = "2.0相容", -- DEPRICATED
		["If you're getting errors with table.setn, enable this"] = "如果你出現table.setn的錯誤啟用此項", -- DEPRICATED
		["Disable Tooltip Scanning"] = "停用工具提示掃瞄", -- DEPRICATED
		["Enable this to skip scanning item tooltips for BoP/BoE/BoU information. This is most likely causing the 'Attempt to index field Rlines' error."] = "啟用此項以防止在工具提示中掃瞄BoP/BoE/BoU的資訊.", -- DEPRICATED
		
		optLock = "鎖定",
		optOptions = "設定界面",
		optBehavior = "行為設定",
		optCursor = "吸附滑鼠",
		optSmartsnap = "快速吸附",
		optSnapoffset = "吸附後滑鼠偏移坐標值",
		optCollapse = "收合捨取按鈕",
		optDragborder = "可移動邊框",
		optLootexpand = "以文字長度調整視窗長度",
		optAltoptions = "當Alt+RightClick顯示菜單",
		optSwiftloot = "當Shift-Cick時不顯示視窗",
		optQualitytext = "顯示物品品質",
		optInfotext = "顯示物品訊息",
		["Show BoP/BoE/BoU"] =  "顯示BoP/BoE/BoU",
		["Show Bind on Pickup/Bind on Equip/Bind on Use text opposite stack size for items"] = "物品中顯示[捨取後梆定][裝備後梆定][使用後梆定]的資訊",
		optLinkAll = "顯示所有的鏈接按鈕",
		optLinkAllVis = "可見: ",
		optLinkAllThreshold = "發佈高於定義等級的物品",
		optLinkAllChannels = "總是發佈物品到...",
		optAppearance = "外觀",
		optQualityborder = "邊框著色",
		optQualityframe = "背景著色",
		optLootqualityborder = "內邊框著色",
		optBgcolor = "整體背景著色",
		optBordercolor = "整體邊框著色",
		optTexColor = "物品圖標著色",
		optHighlightLoot = "高亮拾取",
		optHighlightThreshold = "高亮條件設定", 
		optLootbgcolor = "拾取框背景著色",
		optLootbordercolor = "拾取框邊框著色",
		optInfoColor = "訊息顏色",
		optScale = "縮放",
		optAdvanced = "高級選項",
		optDebug = "Debug 訊息",
		optDefaults = "恢復預設",
		
		descLock = "固定拾取視窗",
		descOptions = "顯示下拉選項",
		descBehavior = "改變XLoot的行為方式",
		descCursor = "讓拾取視窗在你拾取物品時跟隨著滑鼠。",
		descSmartsnap = "讓拾取視窗只是在垂直方向跟隨著滑鼠，這樣在你拾取了一個物品後視窗不會跟著亂跑。",
		descSnapoffset = "設定跟隨點到第一個拾取物品圖標的縱向距離。",
		descCollapse = "隱藏拾取按鈕，如果跟隨選項打開，則將滑鼠移動至下一個視窗。",
		descDragborder = "允許通過拖拽邊框來移動拾取視窗，否則只能拖曳按鈕來移動，可能會導致誤點擊。",
		descLootexpand = "改變視窗的寬度以和物品名稱長度匹配，名稱短則視窗窄，名稱長則視窗寬。",
		descAltoptions = "讓你通過Alt-右擊顯示XLoot菜單，可以停用以避免和其他插件的衝突。",
		descSwiftloot = "避免在自動拾取物品時所產生的些許延遲，你可以在界面選項中設定自動拾取或通過按下特定按鍵（同樣可在界面選項中設定）來自動拾取。",
		descQualitytext = "在物品名稱上方顯示該物品的品質。",
		descInfotext = "在物品名稱的下方顯示物品的信息。",
		descLinkAll = "鏈接所有物品的按鈕，它會彈出一個包含當前所有可用頻道的菜單，讓你把當前的拾取列表發送過去。",
		descLinkAllVis = "切換鏈接所有物品按鈕是否可見。",
		descLinkAllThreshold = "僅鏈接高於限定品質的物品。",
		descLinkAllChannels = "點擊鏈接所有物品時總是發送鏈接至這些頻道。|cFFFF0000如果沒有選擇頻道，點擊鏈接所有物品將顯示菜單。|r",
		descAppearance = "設定XLoot視窗和各個拾取按鈕的顏色，大小，皮膚。",
		descQualityborder = "以最高品質的物品顏色為拾取視窗著色。",
		descQualityframe = "以最高品質的物品顏色為拾取視窗的背景著色。",
		descLootqualityborder = "以品質的顏色為物品邊框著色。",
		descHighlightLoot = "以品質來高亮每個拾取視窗。",
		descHighlightThreshold = "選擇會被高亮的拾取視窗的最低品質。",
		descBgcolor = "改變拾取視窗本身的背景顏色。",
		descBordercolor = "改變視窗本身的邊框顏色。",
		descTexColor = "以品質的顏色為物品圖標/貼圖的邊框上色。",
		descLootbgcolor = "改變所有可拾取物品的背景顏色。",
		descLootbordercolor = "改變所有可拾取物品的邊框顏色。",
		descInfoColor = "改變信息文字顏色",
		descScale = "縮放拾取視窗",
		descAdvanced = "一些並不建議被改變的選項，但也可以試試看。",
		descDebug = "顯示除錯信息",
		descDefaults = "重置XLoot的數據庫並將所有設置恢復到默認值",
		
		qualityQuest = "任務物品",

		["BoP"] = "捨取後梆定",
		["BoE"] = "裝備後梆定",
		["BoU"] = "使用後梆定",

		guiTitle = "XLoot設定",
		
		itemWeapon = "武器",
		
		evHerbs = "草藥採集",
		evOpenNT = "打開-無文本",
		evOpen = "打開",
		
		linkallloot = "連結所有...",
		linkallchanneldesc = "當點選左鍵時，自動發佈所有物品到 %s",
		}
end)