local R = LibStub("AceLocale-2.2"):new("ZOMGReagents")

R:RegisterTranslations("enUS", function() return {
	["Ankh"]					= true,
	["Arcane Powder"]			= true,
	["Flash Powder"]			= true,
	["Maple Seed"]				= true,
	["Stranglethorn Seed"]		= true,
	["Ashwood Seed"]			= true,
	["Hornbeam Seed"]			= true,
	["Ironwood Seed"]			= true,
	["Flintweed Seed"]			= true,
	["Holy Candle"]				= true,
	["Rune of Portals"]			= true,
	["Rune of Teleportation"]	= true,
	["Sacred Candle"]			= true,
	["Soul Shard"]				= true,
	["Symbol of Divinity"]		= true,
	["Symbol of Kings"]			= true,
	["Wild Berries"]			= true,
	["Wild Quillvine"]			= true,
	["Wild Thornroot"]			= true,
	["Corpse Dust"]				= true,
} end)

R:RegisterTranslations("deDE", function() return{
	["Ankh"]					= "Ankh",
	["Arcane Powder"]			= "Arkanes Pulver",
	["Flash Powder"]			= "Blitzstrahlpulver",
	["Maple Seed"]				= "Ahornsamenkorn",
	["Stranglethorn Seed"]		= "Schlingendornsamenkorn",
	["Ashwood Seed"]			= "Eschenholzsamenkorn",
	["Hornbeam Seed"]			= "Hainbuchensamenkorn",
	["Ironwood Seed"]			= "Eisenholzsamenkorn",
	["Flintweed Seed"]			= "Flintgrassaat",
	["Holy Candle"]				= "Heilige Kerze",
	["Rune of Portals"]			= "Rune der Portale",
	["Rune of Teleportation"]	= "Rune der Teleportation",
	["Sacred Candle"]			= "Hochheilige Kerze",
	["Soul Shard"]				= "Seelensplitter",
	["Symbol of Divinity"]		= "Symbol der Offenbarung",
	["Symbol of Kings"]			= "Symbol der Könige",
	["Wild Berries"]			= "Wilde Beeren",
	["Wild Quillvine"]			= "Wilde Federranke",
	["Wild Thornroot"]			= "Wilder Dornwurz",
--	["Corpse Dust"]				= true,
} end)

R:RegisterTranslations("frFR", function() return{
	["Ankh"]					= "Ankh",
	["Arcane Powder"]			= "Poudre des arcanes",
	["Flash Powder"]			= "Poudre aveuglante",
	["Maple Seed"]				= "Graine d'érable",
	["Stranglethorn Seed"]		= "Graine de strangleronce",
	["Ashwood Seed"]			= "Graine de frêne",
	["Hornbeam Seed"]			= "Graine de charme",
	["Ironwood Seed"]			= "Graine de bois de fer",
	["Flintweed Seed"]			= "Graine d'herbe-silex",
	["Holy Candle"]				= "Bougie sanctifiée",
	["Rune of Portals"]			= "Rune des portails",
	["Rune of Teleportation"]	= "Rune de téléportation",
	["Sacred Candle"]			= "Bougie sacrée",
	["Soul Shard"]				= "Fragment d'âme",
	["Symbol of Divinity"]		= "Symbole de divinité",
	["Symbol of Kings"]			= "Symbole des rois",
	["Wild Berries"]			= "Baie sauvage",
	["Wild Quillvine"]			= "Vigneplume sauvage",
	["Wild Thornroot"]			= "Ronceterre sauvage",
--	["Corpse Dust"]				= true,
} end)

R:RegisterTranslations("esES", function() return{
	["Ankh"]					= "Ankh",
	["Arcane Powder"]			= "Partículas Arcanas",
	["Flash Powder"]			= "Partículas explosivas",
	["Maple Seed"]				= "Semillas de arce",
	["Stranglethorn Seed"]		= "Semilla Tuercespina",
	["Ashwood Seed"]			= "Semilla bosqueceniza",
	["Hornbeam Seed"]			= "Semillas de carpinus",
	["Ironwood Seed"]			= "Semilla de maderaférrea",
	["Flintweed Seed"]			= "Semilla de silexia",
	["Holy Candle"]				= "Vela sagrada",
	["Rune of Portals"]			= "Runa de portales",
	["Rune of Teleportation"]	= "Runa de teletransporte",
	["Sacred Candle"]			= "Vela sacra",
	["Soul Shard"]				= "Fragmento de alma",
	["Symbol of Divinity"]		= "Símbolo de Divinidad",
	["Symbol of Kings"]			= "Símbolo de Reyes",
	["Wild Berries"]			= "Frutos silvestres",
	["Wild Quillvine"]			= "Videpluma salvaje",
	["Wild Thornroot"]			= "Raíz de espina salvaje",
--	["Corpse Dust"]				= true,
} end)

R:RegisterTranslations("zhCN", function() return{
	["Ankh"]					= "十字章",
	["Arcane Powder"]			= "魔粉",
	["Flash Powder"]			= "闪光粉",
	["Maple Seed"]				= "枫树种子",
	["Stranglethorn Seed"]		= "荆棘种子",
	["Ashwood Seed"]			= "灰木种子",
	["Hornbeam Seed"]			= "角树种子",
	["Ironwood Seed"]			= "铁木种子",
	["Flintweed Seed"]			= "灼草种子",
	["Holy Candle"]				= "圣洁蜡烛",
	["Rune of Portals"]			= "传送门符文",
	["Rune of Teleportation"]	= "传送符文",
	["Sacred Candle"]			= "神圣蜡烛",
	["Soul Shard"]				= "灵魂碎片",
	["Symbol of Divinity"]		= "神圣符印",
	["Symbol of Kings"]			= "神圣符印",
	["Wild Berries"]			= "野生漿果",
	["Wild Quillvine"]			= "野生刺藤",
	["Wild Thornroot"]			= "野生棘根草",
--	["Corpse Dust"]				= true,
} end)

R:RegisterTranslations("zhTW", function() return{
	["Ankh"]					= "十字章",
	["Arcane Powder"]			= "魔粉",
	["Flash Powder"]			= "閃光粉",
	["Maple Seed"]				= "楓樹種子",
	["Stranglethorn Seed"]		= "荊棘種子",
	["Ashwood Seed"]			= "灰木種子",
	["Hornbeam Seed"]			= "角樹種子",
	["Ironwood Seed"]			= "鐵木種子",
	["Flintweed Seed"]			= "火石草種子",
	["Holy Candle"]				= "神聖蠟燭",
	["Rune of Portals"]			= "傳送門符文",
	["Rune of Teleportation"]	= "傳送符文",
	["Sacred Candle"]			= "聖潔蠟燭",
	["Soul Shard"]				= "靈魂碎片",
	["Symbol of Divinity"]		= "神聖符印",
	["Symbol of Kings"]			= "王者印記",
	["Wild Berries"]			= "野性漿果",
	["Wild Quillvine"]			= "野生羽蔓",
	["Wild Thornroot"]			= "野生棘根草",
--	["Corpse Dust"]				= true,
} end)

R:RegisterTranslations("koKR", function() return {
	["Ankh"]					= "십자가",
	["Arcane Powder"]			= "불가사의한 가루",
	["Flash Powder"]			= "섬광 화약",
	["Maple Seed"]				= " 단풍나무 씨앗",
	["Stranglethorn Seed"]		= "가시덩굴 씨앗",
	["Ashwood Seed"]			= "잿빛나무 씨앗",
	["Hornbeam Seed"]			= "자작나무 씨앗",
	["Ironwood Seed"]			= "강철나무 씨앗",
	["Flintweed Seed"]			= "차돌나무 씨앗",
	["Holy Candle"]				= "신성한 양초",
	["Rune of Portals"]			= "차원이동의 룬",
	["Rune of Teleportation"]	= "순간이동의 룬",
	["Sacred Candle"]			= "성스러운 양초",
	["Soul Shard"]				= "영혼의 조각",
	["Symbol of Divinity"]		= "신앙의 징표",
	["Symbol of Kings"]			= "왕의 징표",
	["Wild Berries"]			= "야생 가지",
	["Wild Quillvine"]			= "야생 가시덩굴",
	["Wild Thornroot"]			= "야생 가시",
--	["Corpse Dust"]				= true,
} end )

R:RegisterTranslations("ruRU", function() return{
	["Ankh"]					= "Крест",
	["Arcane Powder"]			= "Порошок чар",
	["Flash Powder"]			= "Воспламеняющийся порошок",
	["Maple Seed"]				= "Семена клена",
	["Stranglethorn Seed"]		= "Семена из Тернистой долины",
	["Ashwood Seed"]			= "Семена ясеня",
	["Hornbeam Seed"]			= "Семена граба",
	["Ironwood Seed"]			= "Семена железного дерева",
	["Flintweed Seed"]			= "Семена кремень-травы",
	["Holy Candle"]				= "Святая свеча",
	["Rune of Portals"]			= "Руна порталов",
	["Rune of Teleportation"]	= "Руна телепортации",
	["Sacred Candle"]			= "Священная свеча",
	["Soul Shard"]				= "Осколок души",
	["Symbol of Divinity"]		= "Символ божественности",
	["Symbol of Kings"]			= "Символ королей",
	["Wild Berries"]			= "Лесные ягоды",
	["Wild Quillvine"]			= "Дикая перьелоза",
	["Wild Thornroot"]			= "Дикий шипокорень",
--	["Corpse Dust"]				= true,
} end )

R = nil
