local L = Rock("LibRockLocale-1.0"):GetTranslationNamespace("Cartographer_QuestInfo")

L:AddTranslations("koKR", function() return {

-- Core.lua
	["Export"] = "내보내기",
	["Export quest data to other addon."] = "다른 애드온으로 퀘스트 데이터를 내보냅니다.",
	["Quests"] = "퀘스트",
	["Export quest data to Cartographer Quests."] = "카토그래퍼 퀘스트의 데이터를 내보냅니다.",
	["Export data"] = "데이터 내보내기",
	["Export quest data, this will take huge space."] = "",
	["Clear exported data"] = "보낸 데이터 초기화",
	["Clear exported data."] = "보낸 데이터 초기화",
	["Quest Objectives"] = "QuestObjectives",
	["Export quest data to Cartographer QuestObjectives."] = "카토그래퍼 QuestObjectives에 퀘스트 데이터를 보냅니다.",
	["Icon alpha"] = "아이콘 투명도",
	["Alpha transparency of the icon."] = "아이콘의 투명도 값",
	["Icon size"] = "아이콘 크기",
	["Size of the icons on the map."] = "맵에서의 아이콘 크기 설정",
	["Show minimap icons"] = "미니맵 아이콘 표시",
	["Show quest icons on the minimap."] = "미니맵에 퀘스트 아이콘 표시 유무 설정",
	["Show world map button"] = "월드맵 버튼 표시",
	["Show button on the world map."] = "월드맵 버튼의 표시 유무 설정",
	["Make quest log double wide"] = "확장된 퀘스트창 지원",
	["Make the quest log window double wide, this will require UI reload."] = "기본 UI의 퀘스트창을 확장된 형태로 표시해줍니다.",
	["Quest Info"] = "퀘스트 정보",
	["Module description"] = "모듈 설명",
	["Exporting %d quest givers..."] = "%d명의 퀘스트 제공자 체크중...",
	["Total %d quest givers have been exported."] = "총 %d명의 퀘스트 제공자를 체크했습니다.",
	["Clear old exported quest givers first."] = "체크된지 오래된 퀘스트 제공자 부터 제거",
	["Begin exporting new quest givers."] = "새 퀘스트 제공자 체크 시작",
	["Exporting %d quest objects..."] = "%d개의 퀘스트 오브젝트 체크중...",
	["Total %d quest objects have been exported."] = "총 %d개의 퀘스트 오브젝트를 체크했습니다.",
	["Clear old exported objectives first."] = "체크된지 오래된 퀘스트 오브젝트 부터 제거",
	["Begin exporting new quest objectives."] = "새 퀘스트 오브젝트 체크 시작",

-- LocationFrame.lua
	["Close"] = "닫기",

-- Map.lua
	["Quest Start"] = "퀘스트 시작",
	["Quest End"] = "퀘스트 종료",
	["Quest Giver"] = "퀘스트 제공자",
	["Quest Objective"] = "퀘스트 오브젝트",
	["Show active quests"] = "수행 중인 퀘스트 표시",
	["Show all info of active quests in current map."] = "현재 맵 상에서의 모든 활성화된 퀘스트 정보를 표시합니다.",
	["Show available quests"] = "수행 가능한 퀘스트 표시",
	["Show the givers of available quests in current map."] = "현재 맵 상에서의 수행 가능한 퀘스트의 제공자를 표시합니다.",
	["Clear quest icons"] = "퀘스트 아이콘 제거",
	["Clear quest icons generated by QuestInfo"] = "QuestInfo에 의해 생성된 퀘스트 아이콘 제거",
	["Open QuestInfo menu"] = "QuestInfo 메뉴 열기",
	["Alt-Click: "] = "Alt+클릭",
	["Shift-Click: "] = "Shift+클릭",
	["Elite"] = "정예",
	["Rare Elite"] = "희귀 정예",
	["Boss"] = "보스",
	["Name:"] = "이름:",
	["Objective:"] = "오브젝트",
	["Source:"] = "",
	["Level:"] = "레벨:",
	["Location:"] = "위치:",
	["Quests:"] = "퀘스트:",
	["%d Quests"] = "%d개의 퀘스트",

-- QuestFuPatch.lua
	["(done)"] = "(확인)",

-- QuestLogPatch.lua
	[" ..."] = " ...",
	["... more"] = "... 더보기",

-- SeriesFrame.lua
	["Quest Series"] = "퀘스트 연계",
	["Requires:"] = "요구사항:",
	["Sharable"] = "할당가능",
	["Series:"] = "연계:",

} end)
