-- Russian localization by StingerSoft (Eritnull aka Шептун)
local L = Rock("LibRockLocale-1.0"):GetTranslationNamespace("Cartographer_QuestInfo")

L:AddTranslations("ruRU", function() return {

-- Core.lua
	["Export"] = "Экспорт",
	["Export quest data to other addon."] = "Экспортировать данные заданий в другой аддон",
	["Quests"] = "Задания",
	["Export quest data to Cartographer Quests."] = "Экспортировать данные заданий в Картограф-Задания",
	["Export data"] = "Экспорт данных",
	["Export quest data, this will take huge space."] = "Экспортировать данные заданий, это может увеличить объем используемого дискового пространства.",
	["Clear exported data"] = "Очистить экспортированные данные",
	["Clear exported data."] = "Очистить экспортированные данные.",
	["Quest Objectives"] = "Объекты Заданий",
	["Export quest data to Cartographer QuestObjectives."] = "Экспортировать данные заданий в Картограф-Объекты-Заданий",
	["Icon alpha"] = "Прозрачность иконки",
	["Alpha transparency of the icon."] = "Прозрачность иконки",
	["Icon size"] = "Размер иконки",
	["Size of the icons on the map."] = "Размер иконки на карте",
	["Show minimap icons"] = "Показ иконку у мини-карты",
	["Show quest icons on the minimap"] = "Показать иконку задания на мини-карте",
	["Show world map button"] = "Мировая карта",
	["Show button on the world map."] = "Отображать кнопку на мировой карте",
	["Show quest level"] = "Уровень задания",
	["Show quest level in quest log and NPC dialog."] = "Отображение уровня задания в журнале заданий и НИП диалогах.",
	["Make quest log double wide"] = "Сделать журнал заданий из двух секций",
	["Make the quest log window double wide, this will require UI reload."] = "Переделывает журнал заданий из стандартного в расширенный из двух секций, это потребует перезагрузит UI.",
	["Quest Info"] = "Инфо Задания",
	["Module description"] = "Библиотека заданий о местонахождение монстров и другой информации",
	["Exporting %d quest givers..."] = "Экспорт %d дающих задания...",
	["Total %d quest givers have been exported."] = "Всего экспортировано %d дающих задания.",
	["Clear old exported quest givers first."] = "Очистить старых экспортированных НИП дающих задания",
	["Begin exporting new quest givers."] = "Экспортирование новых НИП дающих задания",
	["Exporting %d quest objects..."] = "Экспорт %d объектов заданий...",
	["Total %d quest objects have been exported."] = "Всего экспортировано %d объектов заданий.",
	["Clear old exported objectives first."] = "Очистить старые экспортированные объекты",
	["Begin exporting new quest objectives."] = "Экспортирование новых объектов заданий",
	["GROUP"] = "Группа",

-- LocationFrame.lua
	["Close"] = "Закрыть",

-- Map.lua
	["Quest Start"] = "Начало задания",
	["Quest End"] = "Конец задания",
	["Quest Giver"] = "Дающий задание",
	["Quest Objective"] = "Объект задания",
	["Show active quests"] = "Показать активные задания",
	["Show all info of active quests in current map."] = "Показать всю информацию о активных заданиях на текущей карте",
	["Show available quests"] = "Показать доступные задания",
	["Show the givers of available quests in current map."] = "Показать НИП с доступными заданиями на текущей карте",
	["Clear quest icons"] = "Очистить иконки задания",
	["Clear quest icons generated by QuestInfo"] = "Очистить иконки задания созданные ИнфоЗадания",
	["Open QuestInfo menu"] = "Открыть меню Инфо-Задания",
	["Alt-Click: "] = "Alt-Клик: ",
	["Shift-Click: "] = "Shift-Клик: ",
	["Elite"] = "Элита",
	["Rare Elite"] = "Редкий-Элита",
	["Boss"] = "Босс",
	["Name:"] = "Имя:",
	["Objective:"] = "Объект:",
	["Source:"] = "Источник:",
	["Level:"] = "Уровень:",
	["Location:"] = "Местоположение:",
	["Quests:"] = "Задания:",
	["%d Quests"] = "%d заданий",

-- QuestFuPatch.lua
	["(done)"] = "(выполненный)",

-- QuestLogPatch.lua
	[" ..."] = " ...",
	["... more"] = "... еще",

-- SeriesFrame.lua
	["Quest Series"] = "Серия заданий",
	["Requires:"] = "Требует:",
	["Sharable"] = "Совмест исп.",
	["Series:"] = "Серия:",
} end)
