local L = AceLibrary("AceLocale-2.2"):new("QuestsFu_Details")
L:RegisterTranslations("deDE", function() return {
	["Quest details"] = "Quest Detail's",
	["Custom quest details pane"] = "Benutzerdefiniertes Quest Datail Fenster.",

	["Given by"] = "Bekommen von: ",
	["Required money: "] = "Benötigtes Geld: ",
	["Required item(s):"] = "Benötigte Gegenstände: ",
	["Description"] = "Beschreibung",
	["Rewards"] = "Belohnungen",
	["<not yet cached>"] = "<noch nicht geladen, bitte klicken>",
	["Always receive:"] = "Belohnung ist immer: ",
	["Spell:"] = "Zauber:",
	["Money: "] = "Geld: ",
	["Nothing."] = "Nichts.",
	["Options"] = "Optionen",
	["Share"] = "Teile",
	["Abandon"] = "Entfernen",
	["Close"] = "Schliessen",
	["Choose from:"] = "Auswahl aus: ",

	["%s in %s (%d,%d)"] = "%s in %s (%d,%d)",
	["bunch-of-directions"] = {
		"norden",
		"nördlich",
		"westen",
		"westlich",
		"osten",
		"östlich",
		"süden",
		"südlich",
		"nordwest",
		"nordwestlich",
		"nordost",
		"nordöstlich",
		"südwest",
		"südwestlich",
		"südosten",
		"südöstlich",
		"links",
		"rechts",
		"unten",
		"oben",
		"seiten?",
		"höhlen?",
		"straßen?",
		"inseln?",
		"seen?",
		"wandernt?",
		"dörfer?",
		"küsten?",
		"altare?",
		"dschungel?",
		"ufer?",
		"ruinen?",
		"stadt",
		"städte",
		"flüsse?",
		"lager?",
		"häuser?",
		"minen?",
		"arenas?",
		"berge?",
		"ränder?",
		"ausgrabungsorte?",
		"strand",
		"strände",
		"orte?",
		"garnisonen?",
		"wachtürme?",
		"türme?",
		"docks?",
		"verstecke?",
		"oase",
		"oasen",
	}
} end)