local L = AceLibrary("AceLocale-2.2"):new("QuestsFu_Details")
L:RegisterTranslations("enUS", function() return {
	["Quest details"] = true,
	["Custom quest details pane"] = true,

	["Given by"] = true,
	["Required money: "] = true,
	["Required item(s):"] = true,
	["Description"] = true,
	["Rewards"] = true,
	["<not yet cached>"] = true,
	["Always receive:"] = true,
	["Spell:"] = true,
	["Money: "] = true,
	["Nothing."] = true,
	["Options"] = true,
	["Share"] = true,
	["Abandon"] = true,
	["Close"] = true,
	["Choose from:"] = true,

	["%s in %s (%d,%d)"] = true,
	["bunch-of-directions"] = {
		"north",
		"northern",
		"west",
		"western",
		"east",
		"eastern",
		"south",
		"southern",
		"northwest",
		"northwestern",
		"northeast",
		"northeastern",
		"southwest",
		"southwestern",
		"southeast",
		"southeastern",
		"left",
		"right",
		"bottom",
		"top",
		"upriver",
		"downriver",
		"here",
		"near",
		"sides?",
		"caves?",
		"roads?",
		"islands?",
		"lakes?",
		"wanders?",
		"villages?",
		"coasts?",
		"altars?",
		"jungles?",
		"shores?",
		"ruins?",
		"city",
		"cities",
		"rivers?",
		"camps?",
		"houses?",
		"mines?",
		"arenas?",
		"mountains?",
		"edges?",
		"dig sites?",
		"beach",
		"beaches",
		"towns?",
		"garrisons?",
		"guard towers?",
		"towers?",
		"docks?",
		"dens?",
		"oasis",
		"oases",
	}
} end)
