local L = AceLibrary("AceLocale-2.2"):new("QuestsFu_Details")
L:RegisterTranslations("esES", function() return {
	["Quest details"] = "Detalles de misión",
	--["Custom quest details pane"] = true,
	
	["%s in %s (%d,%d)"] = "%s en %s (%d,%d)",
	["bunch-of-directions"] = {
		"norte",
		"septentrional",
		"oeste",
		"occidental",
		"este",
		"oriental",
		"sur",
		"meridional",
		"noroeste",
		"noroccidental",
		"noreste",
		"nororiental",
		"suroeste",
		"sudoccidental",
		"sureste",
		"sudoriental",
		"izquierda",
		"derecha",
		"bajo",
		"sobre",
		"upriver",
		"downriver",
		"aquí",
		"cerca",
		"lados?",
		"cuevas?",
		"caminos?",
		"islas?",
		"lagos?",
		"deambula?",
		"pueblos?",
		"costas?",
		"altares?",
		"junglas?",
		"orillas?",
		"ruinas?",
		"ciudad",
		"ciudades",
		"ríos?",
		"campamentos?",
		"casas?",
		"minas?",
		"arenas?",
		"montañas?",
		"bordes?",
		"zonas de excavación?",
		"playa",
		"playas",
		"pueblos?",
		"guarniciones?",
		"torres de guardia?",
		"torres?",
		"puerto?",
		"guaridas?",
		"oasis",
	}
} end)
