local L = AceLibrary("AceLocale-2.2"):new("QuestsFu_Details")
L:RegisterTranslations("koKR", function() return {
	["Quest details"] = "퀘스트 상세정보",
	["Custom quest details pane"] = "사용자 퀘스트 상세정보 창",

	["Given by"] = "제공자",
	["Required money: "] = "요구 금액: ",
	["Required item(s):"] = "요구 아이템(들):",
	["Description"] = "상세 설명",
	["Rewards"] = "보상",
	["<not yet cached>"] = "<아직 저장되지 않았습니다.>",
	["Always receive:"] = "항상 받음:",
	["Spell:"] = "주문:",
	["Money: "] = "금액: ",
	["Nothing."] = "없음.",
	["Options"] = "설정",
	["Share"] = "공유",
	["Abandon"] = "포기",
	["Close"] = "닫기",
	["Choose from:"] = "선댁:",

	["%s in %s (%d,%d)"] = "%2$s 내 %1$s (%3$d,%4$d)",
	["bunch-of-directions"] = {
		"북서쪽",
		"북서부",
		"복동쪽",
		"북동부",
		"남서쪽",
		"남서부",
		"남동쪽",
		"남동부",
		"북쪽",
		"북부",
		"서쪽",
		"서부",
		"동쪽",
		"동부",
		"남쪽",
		"남부",
		"왼쪽",
		"오른쪽",
		"아래",
		"상류",
		"하류",
		"여기",
		"근처",
		"옆",
		"동굴",
		"길",
		"섬",
		"호수",
		"마을",
		"해안",
		"제단",
		"우림",
		"물가",
		"폐허",
		"도시",
		"야영지",
		"경기장",
		"경계",
		"해변",
		"바닷가",
		"탑",
		"주둔지",
		"부두",
		"소굴",
		"오아시스",
	}
} end)
