WhisperFu.SpamIntKeysDefaults = {
    {"gold", "%$"},
    {"0", "g", "%$"},
    {"lowest", "price", "gold"},
    {"easily", "track", "order"},
    {"pay", "less", "get", "more"},
    {"wow", "gold", "cheap"}
}

--Many of these were borrowed from SpamSentry :)
WhisperFu.spamKeysDefaults = {
    "0FFW0W",
    "100g.ca",
    "1225game",
    "29games",
    "365ige",
    "4hire",
    "4wowgold",
    "agamegold",
    "agamegold",
    "allW0WG0LDS",
    "auctionwowhouse",
    "buywowgame",
    "championshall.com",
    "eusuppplier",
    "eugspa",
    "forwowgold",
    "gagora",
    "gamenoble",
    "getwowgold",
    "gmauthorization",
    "gmworker",
    "gmworking",
    "gold4guild",
    "goldwithyou",
    "gold-wow.ru",
    "guild4power",
    "helpugame",
    "heygt",
    "hugold",
    "igdollar",
    "igamebuy",
    "igm365",
    "igs365",
    "itembay.ca",
    "itemrate",
    "kgsgold",
    "Make $100 or more",
    "mmoinn",
    "mmospa",
    "oforugold",
    "ogchannel",
    "ogmarket",
    "ogs365",
    "ogs4u",
    "okstar2008",
    "peon",
    "p3ons4hir3",
    "peons4hire",
    "pkpkg",
    "player123",
    "scggame",
    "ssegames",
    "speedpanda",
    "tusongame",
    "tusongold",
    "ucgogogo",
    "vicsale",
    "whoyo.com.tw",
    "wow7gold",
    "wow8gold",
    "wowcoming",
    "woweurope.cn",
    "woweuropegold",
    "wowforever",
    "wowfreebuy",
    "wowgoldsky",
    "wowgoldex",
    "wowjx",
    "wowmine",
    "wowpanning",
    "wowpfs",
    "wowspa",
    "wowstar2008",
    "wowsupplier",
    "zlywy"
};

--[[
--Non-website keywords

    "4hire",
    "Make $100 or more",
    "peon",

    
]]

--[[
--Websites

    "allW0WG0LDS.com",
    "forwowgold",
    "getwowgold.com",
    "guild4power.com",
    "p3ons4hir3.com",
    "scggame.com",
    "tusongold.com",
    "vicsale.com",
    "wow7gold.com",
    "wowpanning.com"

    "100g.ca",
"1225game",
"29games",
"365ige",
"agamegold",
"agamegold",
"auctionwowhouse",
"buywowgame",
"eusuppplier",
"eugspa",
"gagora",
"gamenoble",
"gmauthorization",
"gmworker",
"gmworking",
"gold4guild",
"goldwithyou",
"gold-wow.ru",
"helpugame",
"heygt",
"hugold",
"igdollar",
"igamebuy",
"igm365",
"igs365",
"itembay.ca",
"itemrate",
"kgsgold",
"mmoinn",
"mmospa",
"ogchannel",
"ogmarket",
"ogs365",
"ogs4u",
"okstar2008",
"peons4hire",
"pkpkg",
"player123",
"ssegames",
"speedpanda",
"tusongame",
"ucgogogo",
"whoyo.com.tw",
"wowcoming",
"woweurope.cn",
"woweuropegold",
"wowforever",
"wowfreebuy",
"wowgoldsky",
"wowgoldex",
"wowjx",
"wowmine",
"wowpanning",
"wowpfs",
"wowspa",
"wowstar2008",
"wowsupplier",
"zlywy",
]]