local L = AceLibrary("AceLocale-2.2"):new("QuestsFu")

L:RegisterTranslations("esES", function() return {
	["(done)"] = " (hecho)",
	["(failed)"] = " (fallada)",
	
	["Strata"] = "Estrato",
	["Adjust the strata of this panel (takes effect after you reload your UI)"] = "Ajusta el estrato de este panel (surte efecto tras recargar tu interfaz)",
	["Lock"] = "Bloquear",
	["Lock or unlock this panel"] = "Bloquea o desbloquea este panel",
	
	TOOLTIP_HINT = "|cffeda55fClic|r para abrir el registro de misiones. |cffeda55fMayúsculas-Clic|r para insertar la misión en la caja de edición del chat. |cffeda55fMayúsculas-Ctrl-Clic|r para insertar los objetivos en la caja de edición del chat. |cffeda55fAlt-Clic|r para añadirla al rastreador.",
	["FuBar Tablet"] = "Tooltip de FuBar",
	["Settings for the main FuBar tablet"] = "Ajustes para el Tooltip de FuBar",
	["Show"] = "Mostrar",
	["Choose what information to display"] = "Determina qué información se muestra",
	["Text"] = "Texto",
	["Toolbar text"] = "Texto de la barra",
	["Current"] = "Actuales",
	["Show current # of quests"] = "Muestra el número de misiones que tienes actualmente",
	["Completed"] = "Completadas",
	["Show # of quests completed"] = "Muestra el número de misiones que has completado",
	["Total"] = "Total",
	["Show total possible quests"] = "Muestra el total de las misiones posibles",
	["Last message"] = "Último mensaje",
	["Show last quest status message"] = "Muestra el último mensaje de estado de misión",
	["Levels"] = "Niveles",
	["Show quest levels"] = "Muestra los niveles de las misiones",
	["In QuestsFu"] = "En QuestsFu",
	["Show quest levels in the QuestsFu tooltip"] = "Muestra los niveles de las misiones en el tooltip de QuestsFu",
	["Zone"] = "Zona",
	["Show zone levels in the QuestsFu tooltip"] = "Muestra los niveles de zona en el tooltip de QuestsFu",
	["Impossible quests"] = "Misiones imposibles",
	["Show impossible (red) quests"] = "Muestra las misiones imposibles (rojas)",
	["Show quest zones"] = "Muestra las zonas de las misiones",
	["Current area only"] = "Sólo del área actual",
	["Only show quests for the current zone"] = "Muestra únicamente las misiones de la zona actual",
	["Class quests always"] = "Misiones de clase siempre",
	["Always show class quests"] = "Muestra siempre las misiones de clase",
	["Details"] = "Detalles",
	["Show quest details"] = "Muestra los detalles de misión",
	["Current area details only"] = "Sólo del área actual",
	["Show details for current area quests only"] = "Muestra los detalles solamente para las misiones del área actual",
	["Completed objectives"] = "Objetivos completados",
	["Show completed objectives"] = "Muestra los objetivos completados",
	["Objectives"] = "Objetivos",
	["Color objective completion status"] = "Colorear según el estado de finalización de las misiones",
	["Wrap quest titles"] = "Ajustar títulos de misión",
	["Wrap long quest titles on to multiple lines"] = "Divide los títulos de misión largos en múltiples líneas",
	
	["Color zone names by suggested level"] = "Colorea los nombres de zona según su nivel sugerido",
	["Color"] = "Color",
	["Color settings"] = "Ajustes de color",
	["Title"] = "Título",
	["Color the quest title by difficulty"] = "Colorea los títulos de las misiones según su dificultad",
	["Level"] = "Nivel",
	["Color the quest level by difficulty"] = "Colorea los niveles de las misiones según su dificultad",
	
	["Colors"] = "Colores",
	["Choose custom colors"] = "Elige colores personalizados",
	["Difficulty"] = "Dificultad",
	["Trivial"] = "Trivial",
	["Standard"] = "Estándar",
	["Difficult"] = "Difícil",
	["Very difficult"] = "Muy difícil",
	["Impossible"] = "Imposible",
	["Header"] = "Titular",
	["Completion"] = "Estado",
	["Not started"] = "No comenzada",
	["Underway"] = "En marcha",
	["Done"] = "Acabada",
} end)
